### PR TITLE
Updating AxiosError to include stack trace

### PR DESCRIPTION
**Pull request by despreston**
Related to discussions here https://github.com/axios/axios/issues/2387

Attempt to capture the stack trace at the time the error is created in
order to maintain context about where the error originates from.

### CODE REVIEW

**Review by smoke — APPROVED** [review]

**Review by janhartigan — APPROVED** [review]

**Review by babakontheweb — APPROVED** [review]

**Review by diegood — APPROVED** [review]

**Review by jasonsaayman — APPROVED** [review]
Sweet, this looks good and should significantly improve error reporting :)

**Comment by brianmazzocchi** [comment]
> Soonish (+/- 1 week) I am going to try cut a non breaking release with cherry picks and then soon after a v1

Hi Jason, 
Any idea about the new release? 
Thanks!

**Comment by brianmazzocchi** [comment]
Hi everyone,
Any idea about this new release?

**Comment by jasonsaayman** [comment]
Working hard on getting it out, should be ready very soon

**Pull request merged**
