### PR TITLE
refactor(helpers): optimize the logic of isAxiosError

### PR DESCRIPTION
**Pull request by BlackHole1**
add the judgment of null

### CODE REVIEW

**Review by JasonHK — APPROVED** [review]
Thanks! 😄 I should use the `isObject` function in the first place.

**Comment by johachi** [comment]
Nice! I just discovered this while writing tests for my codebase! Hope this will be merged soon!

**Review by johachi — APPROVED** [review]

**Comment by stephenwade** [comment]
@jasonsaayman Could you take a look at this please? I just ran into an issue that this would fix (passing `null` to `isAxiosError` throws an exception) in my codebase.

**Comment by johachi** [comment]
The forgotten PR 😭

**Comment by jasonsaayman** [comment]
No longer forgotten :)

**Pull request merged**
