### PR TITLE
Update axios.js expose the formDataToStream for public use

### PR DESCRIPTION
**Pull request by fancy45daddy**
Describe your pull request here.

https://github.com/axios/axios/issues/6359

### CODE REVIEW

**Comment by fancy45daddy** [comment]
@jasonsaayman could you check and prove the workflow?

**Comment by jasonsaayman** [comment]
sure

**Review by jasonsaayman — APPROVED** [review]

**Comment by Gerhut** [comment]
I am afraid formDataToStream is only available in http adapter while this PR adds it to the cross-platform interface, which fails the browser checks.

**Comment by jasonsaayman** [comment]
@Gerhut thanks, i will fix this by reverting and then opening a new PR to add it where required

**Pull request merged**
