### PR TITLE
https://github.com/mzabriskie/axios/issues/537

### PR DESCRIPTION
**Pull request by fvicente**
Fixes unhandled browser request cancellation

### CODE REVIEW

**Comment by rubennorte** [comment]
Could you please add a test for this?

**Comment by fvicente** [comment]
@rubennorte 
I would like to help, but I don't know how to simulate a computer going to sleep and then wake up. I tested it in my computer by closing and lifting the monitor of my laptop.
Do you have any ideas?

**Comment by rubennorte** [comment]
I just reviewed the code and you should handle `onabort` as we do in manual cancellations using the cancel token. I suggest you to move onCancel to the request scope and use it in both places.

About the unit tests, you can get the XHR request and manually abort it, to see it axios rejects with the proper error.

**Comment by fvicente** [comment]
Hey @rubennorte,
Sorry I don't understand what you are suggesting, I don't know your library that well. Anyway, I'm not using axios anymore, you can close this issue if you want.
Thanks!

**Comment by nickuraltsev** [comment]
Closing in favor of #1399

**Pull request closed without merging**
