### PR TITLE
Allow baseURL to contain GET query parameters

### PR DESCRIPTION
**Pull request by mmomtchev**
Allow baseURL to contain query parameters (ie don't add / in this case)
#2668

### CODE REVIEW

**Comment by chinesedfan** [comment]
> And consider situations that both params in baseURL and the config, which required to be handled well in adapters.

@mmomtchev For example,

```
    axios('/foo', {
      baseURL: 'http://a.com?b=c',
      params: {
        a: 42
      }
    });
```

**Comment by chinesedfan** [comment]
@mmomtchev If you used the test case I provided, you will find the problem.

**Comment by mmomtchev** [comment]
What behaviour do you expect from that one?

**Comment by chinesedfan** [comment]
@mmomtchev At least it should not be the current result, "http://a.com?b=c/foo&a=42". Maybe "http://a.com/foo?b=c&a=42", which means `config.params` is appended after the params of `config.baseURL`.

**Comment by textbook** [comment]
The problem seems to be that it's written to expect a trailing or leading `&`, i.e. that example would work if it was:

```js
    axios('/foo', {
      baseURL: 'http://a.com?b=c&',
                             // ^
      params: {
        a: 42
      }
    });
```

but that seems like a really awkward thing to expect people to write (and leaves the trailing `&` in the case where you don't add any non-default query params). I don't think this is the right approach to default params; I suggested alternatives [here][1].

  [1]: https://github.com/axios/axios/issues/2668#issuecomment-576811241

**Pull request closed without merging**
