### PR TITLE
Adding HTTP status code to error.toJSON

### PR DESCRIPTION
**Pull request by byrne-greg**
## Issue Summary
Previously it was reported in axios#2947 that the Axios `error.toJSON()` was not outputting the HTTP status code.

For example;
```
const axios = require('axios');

axios.get('/404')
  .catch(function (error) {
    console.log(error.toJSON());
  })
```
would result in the following error message that did not have the HTTP status code of 404 instead only containing the code in the nested in the error `message` string (such as _"Request failed with status code 404"_).

## The Fix
With the following addition to the `toJSON` function's return object in `enhanceError.js`:
```
status: this.response && this.response.status ? this.response.status : null
```
the response HTTP status code will be added when a response is available. If no response is available (i.e. we can't derive a HTTP status code), we will use `null` as the value to imply it is intentionally unavailable.

### createError.spec.js (existing test-class) (test-amendment) 
image

```
npx jasmine **/*/createError.spec.js
npx: installed 13 in 1.863s
Randomized with seed 49409
Started
F.

Failures:
1) core::createError should create an Error that can be serialized to JSON
  Message:
    Expected undefined to be 200.
  Stack:
    Error: Expected undefined to be 200.
        at <Jasmine>
        at UserContext.<anonymous> (/Users/gregbyrne/Personal_Storage/Personal/axios-fork/test/specs/core/createError.spec.js:26:25)
        at <Jasmine>
```

### enhanceError.spec.js (existing test-class) (new test) 
image

```
npx jasmine **/*/enhanceError.spec.js
npx: installed 13 in 1.481s
Randomized with seed 46485
Started
..F

Failures:
1) core::enhanceError should serialize to JSON with a status of null when there is no response
  Message:
    Expected undefined to equal null.
  Stack:
    Error: Expected undefined to equal null.
        at <Jasmine>
        at UserContext.<anonymous> (/Users/gregbyrne/Personal_Storage/Personal/axios-fork/test/specs/core/enhanceError.spec.js:24:32)
        at <Jasmine>

3 specs, 1 failure
Finished in 0.01 seconds
```

## Passing Test with addition
Execution specifically on the `*Error.spec.js` tests
```
npx jasmine **/*/*Error.spec.js 
npx: installed 13 in 1.883s
Randomized with seed 07705
Started
.....
5 specs, 0 failures
Finished in 0.012 seconds
```

Execution with `npm test`
```
Chrome 81.0.4044 (Mac OS X 10.15.4): Executed 211 of 211 SUCCESS (3.457 secs / 3.403 secs)
....................................................
Firefox 75.0.0 (Mac OS X 10.15.0): Executed 211 of 211 SUCCESS (2.179 secs / 2.146 secs)
```
_Side Note: Cannot seem to run these in Safari. When it launches the karma runner, it opens the Safari browser with a Choose file modal already focused to a redirect.html. Also it hangs running on Opera which I don't believe I have installed. When I sigkill, testing moves on to the the bundlesize test_

## Internal client.html addition
Additionally, I've added a display to the internal client.html which is started using `npm start`.

This now displays the result of an error in the main display (under an _Error_ div) that uses `toJSON()` as well as displaying the error object in the console.

### No Error
On startup
image

Successful response / no error
image

### Error
With a 404 error
image

### CODE REVIEW

**Comment by byrne-greg** [comment]
After submitting this PR did I realise that there is 123 (at time of writing) open PR's on this project awaiting integration.

Is it safe to say this one likely won't be merged in anytime soon?

**Comment by jasonsaayman** [comment]
Hi,

I will review soon. We are trying to release a v0.20 as soon as possible.

**Comment by atlanteh** [comment]
Can this please be merged? We have hacks in multiple places to fix this. thx :)

**Comment by byrne-greg** [comment]
@emilyemorehouse @jasonsaayman  
do you know if this is on the roadmap for release? it was previously considered for v0.20

**Pull request merged**
