### PR TITLE
updated interceptor use type definition to remove interceptor options parameter from use method for response interceptors

### PR DESCRIPTION
**Pull request by amitsainii**
With Axios `1.x` we introduced an optional third argument for our interceptor `use` function. When I looked at the source code, I realized this third param of type `AxiosInterceptorOptions` is only used for request interceptor.  
The issue I'm reporting is related to the typescript definition for the use method. Currently, when it comes to this third parameter, type definitions don't distinguish between request and response interceptors. Because of this currently, this third argument can be used on the response interceptor as well without typescript yelling at you. This is misguiding for our consumers as they may end up using `runWhen` on response interceptors which won't do anything.

This PR fixes this problem by using conditional type for `use` method wherein `AxiosResponseInterceptorUse` does not include an options parameter in the type definition.

Fixes: [#5074](https://github.com/axios/axios/issues/5074)

### CODE REVIEW

**Review by jasonsaayman — CHANGES_REQUESTED** [review]
Thanks for the contribution and it looks good, however can you please pull the changes to the index.d.cts too?

**Comment by amitsainii** [comment]
@jasonsaayman I can't seem to understand what you mean. There isn't any `index.d.cts` file and I already made the type definition changes to `index.d.ts`. Can you please help me understand what this is about 🥺

**Comment by jasonsaayman** [comment]
@amitsainii the file is over [here](https://github.com/axios/axios/blob/v1.x/index.d.cts) we use two sets of types one for CommonJS and one for ESM 😄

**Comment by amitsainii** [comment]
Thanks, @jasonsaayman I added the type definitions to `index.d.cts` 👍. The reason I wasn't able to locate it before was that I last pulled `1.x` 15 days back and `index.d.cts` is added 13 days back 😄

**Comment by amitsainii** [comment]
Hi @jasonsaayman, will you be able to look at this PR?

**Comment by amitsainii** [comment]
@jasonsaayman Please let me know if anything is stopping this from getting merged. I'd be happy to incorporate it if something else's needed

**Comment by amitsainii** [comment]
@jasonsaayman  @DigitalBrainJS This PR is in a mergeable state for a long time, will you please be able to look at it?

**Comment by amitsainii** [comment]
@jasonsaayman @DigitalBrainJS This PR fixes an issue with the typings for use method on the interceptor. @jasonsaayman has already verified this 6 months back. Can you guys look into it?

**Review by DigitalBrainJS — APPROVED** [review]

**Comment by amitsainii** [comment]
@DigitalBrainJS Is this good to go in our next release? In case there are any blockers please let me know, thanks.

**Comment by amitsainii** [comment]
@DigitalBrainJS Can we unblock this, please? I don't think any further changes are needed here. Please let me know if you need more info related to the changes

**Review by jasonsaayman — APPROVED** [review]

**Comment by amitsainii** [comment]
@jasonsaayman @DigitalBrainJS This has approval from both of you. Please let me know if there's still something that's stopping this from getting merged.

**Comment by jasonsaayman** [comment]
> @jasonsaayman @DigitalBrainJS This has approval from both of you. Please let me know if there's still something that's stopping this from getting merged.

sorry must have fallen by the way side with other things coming in but I am merging this todya

**Pull request merged**
