### PR TITLE
Fixing #385 - instance.defaults changes global object

### LINKED ISSUE #385: instance.defaults changes global object
If I have two instances of axios created with axios.create and I set a default header on one, it also changes it on all the other ones in existence.

```
var instance1 = this.oauthService = axios.create({});
var instance2 = this.oauthService = axios.create({});

instance2.defaults.headers.common['Authorization'] = 'askdjfaksdjf';
```

Both instance1 and 2 now have the Authorization header changed.  I believe the problem is that the util.merge operation doesn't do deep merging, though as you see below, only if the result[key] and val are both objects, does it do a recursive merge, otherwise it assigns the value by reference.  

```
function merge(/\* obj1, obj2, obj3, ... */) {
  var result = {};
  function assignValue(val, key) {
    if (typeof result[key] === 'object' && typeof val === 'object') {
      result[key] = merge(result[key], val);
    } else {
      result[key] = val;
    }
  }

  for (var i = 0, l = arguments.length; i < l; i++) {
    forEach(arguments[i], assignValue);
  }
  return result;
}
```

### PR DESCRIPTION
**Pull request by yanivefraim**
This will fix the problem of instance's headers being overriding other instances' headers. 

According to https://github.com/mzabriskie/axios/issues/370 we want to have some kind of "whitelist" for keys we do want to deep clone. I went over `auth`, `transformRequest` etc. and did not find a similar problem.

I think that this solution is a hack, but it can temporarily fix this (urgent) issue. 

For long term I think we should reconsider this and maybe think of better approach here.

I understand If this approach (hack) is not acceptable, and I would love to discuss a solution and help fixing it!

This will fix #385

### CODE REVIEW

**Comment by yanivefraim** [comment]
Ome comment: I used JSON.parse/stringify trick to avoid using libraries like loadash. A better solution might be writing our own function / importing only lodash's required method

**Comment by nickuraltsev** [comment]
Here are my thoughts:

- `merge` function should not be specific to axios domain logic
- We should create a new function in [`core`](https://github.com/mzabriskie/axios/tree/master/lib/core) instead. For example: `mergeConfigs`.
- The new function can use `merge` if necessary.
- We can try to use `lodash.cloneDeep`, but we should make sure it works in IE8 (as axios still supports IE8) and it's not too big. I'm ok with writing our own function too.

**Comment by yanivefraim** [comment]
Copying only headers by value (whitelisting) will not completely solve the problem. If tomorrow we have another nested default value, it will be copied by reference and can then overwrite all defaults.
 
A better solution is to copy all defaults by value before merging. This way, every axios instance has a copy of the defaults object that can be mutated and will only affect that instance.

@nickuraltsev - Can you plz look at my last commit? WDYT?

**Comment by yanivefraim** [comment]
ping... ? 
@nickuraltsev @mzabriskie

**Comment by nickuraltsev** [comment]
I don't think it's safe to copy all defaults as you suggested. Look at the issue #370 for example. Creating a deep copy of the `defaults` will break apps that override `defaults.httpAgent` or `defaults.httpsAgent`. 

I would suggest to do the following:

- Define what config options can be inherited. For example, I don't think we should support inheritance of options like `data` and `params`. In other words, I think it should be possible to set `data` at the request level, but not at the instance or global levels. 
- For each option that can be inherited, we should define whether to merge or overwrite its values. For example, we should *not* merge `httpsAgent` objects. (I cannot think of a example of a config option whose values need to be merged, so maybe it does not exist at all.)

Separately, creating copying / merging the configuration objects in the constructor is not enough. I think it should be done in the `request` method as well. Otherwise, changing the request config in an interceptor will change the instance configuration.

**Comment by thundo** [comment]
Any update on this? Instances at the moment are quite crippled :/

**Comment by CreativeKoen** [comment]
Any update on this? @nickuraltsev ?

**Comment by brunocascio** [comment]
Any update, please?

**Comment by yanivefraim** [comment]
I'll gladly help here, but it is impossible to work when owners are not responding (it takes too much time to get a response here). For a project with so many users we must have an option for contributors to feel comfortable to add PRs / fix issues.

@nickuraltsev - fyi

**Comment by omeb** [comment]
sounds like a great idea to me

**Comment by yoyo837** [comment]
#1395 has been merged.

**Comment by emilyemorehouse** [comment]
Closing, as this issue was resolved in #1395. 🙌

**Pull request closed without merging**
