### PR TITLE
fix: exporting missing exports in type definition `index.d.ts`

### PR DESCRIPTION
**Pull request by trim21**
close https://github.com/axios/axios/issues/5001

`index.d.ts` exports class `Axios`, `AxiosHeaders`, `AxiosError`, `CanceledError`, but they are not exported in runtime code.

### CODE REVIEW

**Comment by arthurfiorette** [comment]
Should this PR also export everything that axios v0 used to export? Maybe also add the newly exported `AxiosHeaders` class...

**Comment by trim21** [comment]
`AxiosHeaders` is already added to exports in this PR.

**Comment by trim21** [comment]
> Should this PR also export everything that axios v0 used to export? Maybe also add the newly exported `AxiosHeaders` class...

Just checkout v0, it exports   `Axios`,  `AxiosError`,  `CanceledError`, so also already done.

**Comment by jasonsaayman** [comment]
I will release 1.0.1 tonight with this change and anything else that is crucial.

**Pull request merged**
