### PR TITLE
Added generic `AxiosAbortSignal` TS interface to avoid importing AbortController polyfill

### LINKED ISSUE #4124: Usage of AbortController ist breaking for setup without DOM Library
#### Describe the bug
Axios has been using the `AbortController` from the DOM library since version 0.22.0 (# 3305). Since then, the DOM library has to be stored in tsconfig.json. Without DOM the new version is breaking for our setup and can no longer be used.

#### To Reproduce
Use `axios.get()` without DOM Library. To reproduce change `tsconfig.json` to eg.:

```
...
    "lib": ["ES2020"],
...
```

#### Expected behavior
axios should work without DOM. Maybe there is an alternative for `AbortController`?

#### Environment
 - Axios Version 0.22.0
 - Adapter http
 - Browser none
 - Node.js Version 14.18.0
 - OS: macOS 11.6

#### Additional context/Screenshots
Given Exception:

```
> @smirowstanitzok/trendytag-sdk@3.1.2 build /home/runner/work/trendytag-sdk/trendytag-sdk
> tsc

Error: node_modules/axios/index.d.ts(81,12): error TS2304: Cannot find name 'AbortSignal'.
Error: src/index.ts(189,13): error TS2322: Type 'unknown' is not assignable to type 'AxiosResponse<ContactFormResponse> | undefined'.
  Type 'unknown' is not assignable to type 'AxiosResponse<ContactFormResponse>'.
Error: src/index.ts(189,88): error TS2345: Argument of type 'ContactForm' is not assignable to parameter of type 'ContactFormResponse'.
  Property 'messageId' is missing in type 'ContactForm' but required in type 'ContactFormResponse'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @smirowstanitzok/trendytag-sdk@3.1.2 build: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @smirowstanitzok/trendytag-sdk@3.1.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-10-01T08_27_20_612Z-debug.log
Error: Process completed with exit code 2.
```

### PR DESCRIPTION
**Pull request by DigitalBrainJS**
Fixes #4124 by adding a generic AbortSignal interface.

### CODE REVIEW

**Comment by vishalailani** [comment]
@DigitalBrainJS / @jasonsaayman, i am also facing the same issue. is it merged ? if not please merge this as all checks have already passed.

**Comment by j4ys0n** [comment]
+1 can this be merged please? my build is failing because of the issue this fixes.

thank you!

**Comment by juditvarro** [comment]
+1 
Could you please give an estimation @DigitalBrainJS / @jasonsaayman  on when can we expect that this will be merged? Thank you!

**Comment by DigitalBrainJS** [comment]
@juditvarro Unfortunately, I can't provide an estimation as I'm not a member of the Axios team. The project is maintained by @jasonsaayman and @chinesedfan, so everything is up to them.

**Comment by smolster** [comment]
+1 @jasonsaayman @chinesedfan

**Comment by nyalsadiq** [comment]
Is there anything we can do to help get this merged soon? @jasonsaayman @chinesedfan

**Pull request merged**
