### PR TITLE
use qs style by default for params

### PR DESCRIPTION
**Pull request by bertho-zero**

### CODE REVIEW

**Comment by bertho-zero** [comment]
To keep the current behavior it will be necessary to use the `paramsSerializer: 'simple'` option. (depth arrays of 1, object json.stringified, skip null values)

If you just want to use brackets you can use the `paramsSerializer: 'brackets'` option.

The default formatting is now more complete and corresponds to qs.

The ideal would be to be able to remove the compatibility options and return to the documentation of a library as qs to use paramsSerializer as soon as the configuration is no longer the default one.

**Comment by bertho-zero** [comment]
I may have an answer one day...

**Comment by bertho-zero** [comment]
When an object is passed as `paramsSerializer`, it must be passed as options to `encodeParams`.

And we should add the option `arrayFormat: 'repeat'` (to fix https://github.com/axios/axios/issues/1443 like qs)

```js
axios.get(
  "/url",
  { params: { a: ["b", "c"] } },
  { paramsSerializer: { arrayFormat: "indices" } }
);
// '/url?a[0]=b&a[1]=c'

axios.get(
  "/url",
  { params: { a: ["b", "c"] } },
  { paramsSerializer: { arrayFormat: "brackets" } }
);
// '/url?a[]=b&a[]=c'

axios.get(
  "/url",
  { params: { a: ["b", "c"] } },
  { paramsSerializer: { arrayFormat: "repeat" } }
);
// '/url?a=b&a=c'
```

**Comment by jasonsaayman** [comment]
On this I don't think this should be implement as mentioned previously if you'd like to use another format, you can set a custom paramsSerializer as follows:

```js
axios.defaults.paramsSerializer: function(params) {
  // return a query string
}
```

Using the qs library:
```js
axios.defaults.paramsSerializer: function(params) {
  return qs.stringify(params, { indices: false }); // param=value1&param=value2
}
```

**Pull request closed without merging**
