### PR TITLE
Added localAddress config option

### PR DESCRIPTION
**Pull request by DavyJohnes**

### CODE REVIEW

**Comment by DavyJohnes** [comment]
> Everything seems to be alright

Hi, could u please suggest, what I need to do to merge this PR?

**Comment by DavyJohnes** [comment]
@dantalian ?

**Comment by ericklp** [comment]
Hi All, can this pull request be merged? I really need this feature in a project.

**Comment by nathan818fr** [comment]
:+1:

**Comment by chinesedfan** [comment]
Closed in favor of #2808.

**Comment by DavyJohnes** [comment]
@chinesedfan why can't we just merge and release this PR in order to provide useful feature right now, and then work on long term "More flexible ways to customize adapters" task?
Closing this PR in favor of https://github.com/axios/axios/issues/2808 sounds strange to me, since it isn't going to be merged soon, as far as I understand.

**Comment by chinesedfan** [comment]
@DavyJohnes Considering the active status of axios (npm owners are offline in most days), I think this feature has low priority. And closing is not meaning abandoned. Later ideas can be tracked in #2808. Thanks for understanding.

**Pull request closed without merging**
