### PR TITLE
Fixed The timeoutErrorMessage property in config not work with Node.js (fixes #3580)

### LINKED ISSUE #3580: The timeoutErrorMessage property in config not work with Node.js
#### Describe the bug
The timeoutErrorMessage property in config not work with Node.js, expected custom error message, got "**timeout of \*ms exceeded**"

#### To Reproduce
```js
it('should respect the timeoutErrorMessage property', function (done) {

    server = http.createServer(function (req, res) {
      setTimeout(function () {
        res.end();
      }, 1000);
    }).listen(4444, function () {
      var success = false, failure = false;
      var error;

      axios.get('http://localhost:4444/', {
        timeout: 250,
        timeoutErrorMessage: 'oops, timeout',
      }).then(function (res) {
        success = true;
      }).catch(function (err) {
        error = err;
        failure = true;
      });

      setTimeout(function () {
        assert.strictEqual(success, false, 'request should not succeed');
        assert.strictEqual(failure, true, 'request should fail');
        assert.strictEqual(error.code, 'ECONNABORTED');
        assert.strictEqual(error.message, 'oops, timeout');
        done();
      }, 300);
    });
});
```

#### Expected behavior
Expected: oops, timeout
Got: timeout of 250ms exceeded

#### Environment
- Axios Version: 0.21.1
- Adapter: HTTP
- Browser: none
- Browser Version: none
- Node.js Version: 12.19.0
- OS: MacOS 10.14
- Additional Library Versions: none

#### Additional context/Screenshots
image

### PR DESCRIPTION
**Pull request by duibu05**
This PR fixes #3580, the issue is that when send axios request in Node.js contains timeout, timeoutErrorMessage properties in config then fired timeout, the error message is not the customized timeoutErrorMessage but "timeout of *ms exceeded". This PR fixes that problem.

### CODE REVIEW

**Review by daniel-julius-sam — CHANGES_REQUESTED** [review]
Isn't is better to declare `var timeoutErrorMessage = ''` first then check if config has a `timeoutErrorMessage` property and if so assign it this value, else the default time out error message should be displayed. This will ensure that the default message is not unnecessarily created if config already has the error message.

```
var timeoutErrorMessage = '';
if (config.timeoutErrorMessage) {
  timeoutErrorMessage = config.timeoutErrorMessage;
} else {
  timeoutErrorMessage = 'timeout of ' + timeout + 'ms exceeded';
}
```

**Comment by duibu05** [comment]
> Isn't is better to declare `var timeoutErrorMessage = ''` first then check if config has a `timeoutErrorMessage` property and if so assign it this value, else the default time out error message should be displayed. This will ensure that the default message is not unnecessarily created if config already has the error message.
> 
> ```
> var timeoutErrorMessage = '';
> if (config.timeoutErrorMessage) {
>   timeoutErrorMessage = config.timeoutErrorMessage;
> } else {
>   timeoutErrorMessage = 'timeout of ' + timeout + 'ms exceeded';
> }
> ```

@daniel-julius-sam  done

**Comment by daniel-julius-sam** [comment]
Please link this PR to the relevant issue by including `fixes  #3580` in the PR description.

**Comment by duibu05** [comment]
fixes #3580

**Comment by djs113** [comment]
That's not what I meant, you should add `fixes #3580` exactly in the main message describing this PR just beneath the title, so that it gets linked to the issue it solves. Like how I have done in this PR. [https://github.com/axios/axios/pull/3961#partial-pull-merging]()

**Comment by duibu05** [comment]
@djs113 Got it, already updated. Please approve this workflow.

**Comment by djs113** [comment]
I'm not a mainainer, @jasonsaayman please approve this.

**Comment by jasonsaayman** [comment]
@duibu05 please can you mend the conflict?

**Comment by duibu05** [comment]
> 



> @duibu05 please can you mend the conflict?



> @duibu05 please can you mend the conflict?

@jasonsaayman done

**Pull request merged**
