### PR TITLE
fix(core): fixed config merging bug

### PR DESCRIPTION
**Pull request by Aakash-Rana**
Code Change is related to the bug raised at https://github.com/axios/axios/issues/6667
**Fix: Distinguish Case-Sensitive Keys in Params Merging**

This PR addresses an issue where mergeConfig treated parameters with differing cases (e.g., region vs. Region) as identical due to findKey converting keys to lowercase, causing unintended value overwrites. The findKey function has been updated to preserve the original case during comparisons, ensuring case-sensitive merging and distinct handling for parameters with similar names but different cases.

**CHANGES:**
- Updated findKey to avoid case conversion, supporting distinct parameter keys

### CODE REVIEW

**Review by DigitalBrainJS — CHANGES_REQUESTED** [review]
Unfortunately, the PR doesn't fix the bug. If you try to run the tests, you may find out that it just makes the findKey utility useless and breaks other related code. The problem is inside [mergeConfig](https://github.com/axios/axios/blob/cda671af81ca87a00c6bf5a07bffcb07468756d3/lib/core/mergeConfig.js#L17) util due to function params overlapping. Every merge handler [is called](https://github.com/axios/axios/blob/cda671af81ca87a00c6bf5a07bffcb07468756d3/lib/core/mergeConfig.js#L101) with the property name as the third argument, but [mergeDeepProperties](https://github.com/axios/axios/blob/cda671af81ca87a00c6bf5a07bffcb07468756d3/lib/core/mergeConfig.js#L34) and [getMergedValue](https://github.com/axios/axios/blob/cda671af81ca87a00c6bf5a07bffcb07468756d3/lib/core/mergeConfig.js#L22) expect `caseless` argument instead so this causes the bug.
So we can fix this by inserting the missing prop argument into the functions definition and fixing their calls
```js
function getMergedValue(target, source, prop, caseless) {...}
function mergeDeepProperties(a, b, prop, caseless) {
// fix call
headers: (a, b, prop) => mergeDeepProperties(headersToObject(a), headersToObject(b), prop, true)
```

**Comment by Aakash-Rana** [comment]
@DigitalBrainJS 
Thank you for reviewing the PR and for your guidance! I see the issue now. I had adjusted the function definitions to include prop and correct the calls as suggested. 

I appreciate your detailed feedback—it’s very helpful.

**Comment by Aakash-Rana** [comment]
Hello @DigitalBrainJS 
Could you please check the PR
Thanks

**Review by DigitalBrainJS — APPROVED** [review]

**Comment by DigitalBrainJS** [comment]
@race-of-sloths score 2

**Comment by race-of-sloths** [comment]
@DigitalBrainJS Thank you for calling!
    
@Aakash-Rana Thank you for the contribution! Join [Race of Sloths](https://race-of-sloths.com) by simply mentioning me in your comment/PRs description and start collecting Sloth Points through contributions to open source projects.

<details><summary>What is the Race of Sloths</summary>
<p>
Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag @race-of-sloths inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard](https://race-of-sloths.com/leaderboard)
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile](https://race-of-sloths.com/profile/Aakash-Rana)

For maintainers:
- Score pull requests that participate in the Race of Sloths
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website](https://race-of-sloths.com) for additional details!
</p>
</details> 

<details>
<summary>Bot commands</summary>

- For contributors
  - **Include a PR:** `@race-of-sloths include` to enter the Race with your PR
- For maintainers:
  - **Invite contributor** `@race-of-sloths invite` to invite the contributor to participate in a race or include it, if it's already a runner.
  - **Assign points:** `@race-of-sloths score [1/2/3/5/8/13]` to award points based on your assessment.
  - **Reject this PR:** `@race-of-sloths exclude` to send this PR back to the drawing board.
  - **Exclude repo:** `@race-of-sloths pause` to stop bot activity in this repo until `@race-of-sloths unpause` command is called

</details>

**Pull request merged**
