### PR TITLE
Updating the docs to use Promises. Fixes #1042

### LINKED ISSUE #1042: Remove `axios.all` and `axios.spread`
Those helpers can easily be replaced with native features (`Promise.all` and ES6 parameter destructuring) or specialized libraries, so we should restrict our API to HTTP-related methods.

We can deprecate them in 0.x and completely remove then in 1.0.

### PR DESCRIPTION
**Pull request by franciscop**
Upgraded to use native promises and destructuring on the arguments. The syntax is supported natively in the same situations as for the Promises. Follows the discussion in https://github.com/axios/axios/issues/1042

### CODE REVIEW

**Comment by saiqulhaq** [comment]
when this PR is merged?

**Comment by jcrben** [comment]
@rubennorte @emilyemorehouse this is just a docs change, should be pretty straightforward to merge

**Comment by jcrben** [comment]
If the plan is to drop a feature in the future, I would prefer to warn users immediately in the docs. The sooner we can get this out there, the less we will force users to rewrite their code.

Also, in this case it's recommending a feature which is already widely-supported and understood.

**Comment by chinesedfan** [comment]
Closed in favor of #2727.

**Pull request closed without merging**
