### PR TITLE
Integrate with gitpod

### PR DESCRIPTION
**Pull request by nisarhassan12**
Hi! there :slightly_smiling_face:

This PR simplifies code contributions by fully automating the dev setup with Gitpod (a free online VS Code-like IDE) for contributing. With a single click, it'll launch a workspace and automatically:

- clone the axios repo.
- install the dependencies.
- run `npm start`.

So that anyone interested in contributing can start straight away.

You can give it a try on My Fork of the repo:

https://gitpod.io/#https://github.com/nisarhassan12/axios/

image

### CODE REVIEW

**Comment by nisarhassan12** [comment]
Rebased on top of latest master.

**Comment by nisarhassan12** [comment]
Rebased on top of the latest master @mzabriskie @nickuraltsev

**Comment by jasonsaayman** [comment]
@chinesedfan @timemachine3030 What do you guys think would be helpful?

**Review by chinesedfan — CHANGES_REQUESTED** [review]
#1958 has already mentioned GitPod. I can accept a tiny change to move the link from `examples/README.md` to the main `README.md`.

**Comment by nisarhassan12** [comment]
Thanks, @chinesedfan Sounds good.

**Comment by jasonsaayman** [comment]
@ nisarhassan12 will you be making these changes soon? I will so long tag this for you into the next proposed release.

**Comment by nisarhassan12** [comment]
@jasonsaayman Thanks. I have made the requested change with a slight modifcation.

**Pull request merged**
