### PR TITLE
Fix `params` merging

### PR DESCRIPTION
**Pull request by zackseuberling**
Fixes bug introduced in 0.19.0 where request params are not being merged correctly with default instance params. See bug #2190 for more information

According to the documentation:

> The available instance methods are listed below. The specified config will be merged with the instance config.

Tests were failing because of the change to merge params, so hopefully my update to the tests is _correct_ … and passes

### CODE REVIEW

**Comment by nothingismagick** [comment]
Nice job @zackseuberling

**Comment by kodmunki** [comment]
0.19.0 is breaking our services. The root cause appears to be what this is fixing. What kind of timeline on a merge and release? 🤓🍻

**Comment by jasonsaayman** [comment]
@kodmunki I cannot merge the changes, we will need to wait for @emilyemorehouse. I'm sure it will be done soon.

**Comment by bios21** [comment]
I think maybe this PR should be passed alongside this one: https://github.com/axios/axios/pull/2207 because more than one BC was induced by `mergeConfig` function.

**Comment by samerdernaika** [comment]
plz merge it

**Comment by code-a-cola** [comment]
Do we have an update as to when this is getting merged?

**Comment by nothingismagick** [comment]
I would just like to say that we (at quasarframework) are still recommending that people pin 0.18.1, and I have to agree that @code-a-cola is right - it would be good to update this issue.

**Comment by ibrainventures** [comment]
@emilyemorehouse  .. thanks for your work on this project .. it qould be great and neefull to see this pr merged! :-)

**Comment by avindra** [comment]
I ran `grunt karma:single` against master after https://github.com/axios/axios/pull/2207 got merged.

@zackseuberling your test breaks against master, so PR 2207 seemed to be solving another issue:

```
Chrome 77.0.3865 (Linux 0.0.0) core::mergeConfig should merge auth, headers, params, proxy with defaults FAILED
	Expected $.params to have properties
	    foo: 'test'
	    at UserContext.<anonymous> (webpack:///test/specs/core/mergeConfig.spec.js:50:78 <- test/specs/core/mergeConfig.spec.js:96:83)
................................................................................
.....................................
Firefox 68.0.0 (Linux 0.0.0) core::mergeConfig should merge auth, headers, params, proxy with defaults FAILED
	Expected $.params to have properties
	    foo: 'test'
	@webpack:///test/specs/core/mergeConfig.spec.js:50:78 <- test/specs/core/mergeConfig.spec.js:96:83
................................................................................
```

**Comment by janpantel** [comment]
For everyone looking for a workaround you could use mine (might not apply to all):

`npm i qs`

```
axios.interceptors.request.use(config => {
    config.paramsSerializer = params => {
        params = { ...params, mySpecialValue: 'foo' };
        return qs.stringify(params);
    };
    return config;
}
```

**Comment by Alanscut** [comment]
@zackseuberling , code is updated, please resolve the conflicts, thanks!

**Comment by yasuf** [comment]
would you mind adding tests to this change?

**Comment by yasuf** [comment]
and fixing the existing tests

**Comment by zackseuberling** [comment]
@yasuf I can't get the test suite to run for me, so it is quite hard for me to fix or change any tests

**Comment by chinesedfan** [comment]
Closed in favor of #2656. Cheers.

**Pull request closed without merging**
