### PR TITLE
Set maxBodyLength on follow-redirects to match maxContentLength on AxiosOptions

### PR DESCRIPTION
**Pull request by mividtim**
Set the `maxBodyLength` on the options sent to `follow-redirects` to match the `AxiosOptions` property `maxContentLength`, so `axios` can support content lengths greater than 10mb.

Addresses https://github.com/axios/axios/issues/1286

### CODE REVIEW

**Comment by mividtim** [comment]
@Khaledgarbaya Please review and merge.

**Comment by amsross** [comment]
pretty please?

**Comment by mividtim** [comment]
Does this project have any active maintainers? I have two open PRs, passing tests, improving functionality, and not a peep for almost a month, after several pings.

**Comment by amsross** [comment]
The [commit history](https://github.com/axios/axios/commits/master) doesn't seem _too_ terrible stale, so hopefully it's not dead.

**Comment by emilyemorehouse** [comment]
There was a call for assistance about a month ago (http://www.mattzabriskie.com/blog/axios-help-wanted). A few of us have stepped up, along with the original owners, and are working hard to get through the backlog of issues and PRs. Bear with us!

**Comment by mividtim** [comment]
@emilyemorehouse Sorry for being short. I just started using this project fairly recently, so I must have missed the call to action, or it just didn't reach me on channels I was watching. I'd love to pitch in any way I can. Could you lead me in the right direction?

Thanks for the merge!

**Comment by emilyemorehouse** [comment]
@mividtim No worries! The squeaky wheel gets the grease, right? In terms of helping out, I've been trying to clear out the backlog of issues by determining which ones are really bugs and which are issues with a user's implementation. I'll usually start by providing a working example (unless I can reproduce a bug) or even just pinging old issues to see if they'll still respond. Feel free to reach out to me if you want more info or collaboration, I'm quite accessible on the internet.

@dnfield I'll ping the person who's acting as a release manager, we definitely need an updated release.

**Comment by emilyemorehouse** [comment]
I'm now a person who can cut releases 🤷‍♀️
So... this is released in 0.18.0!

**Pull request merged**
