### PR TITLE
bugfix to allow working HTTPS via SSL/HTTPS Proxy #1885

### PR DESCRIPTION
**Pull request by darashenka**
Fix bug https://github.com/axios/axios/issues/1885 
As well as the bug accessing HTTPS URLs with HTTPS Proxy.

### CODE REVIEW

**Comment by bcornies** [comment]
Are there any plans for merging this? I've run into an issue connecting to an https url via a corporate proxy. I manually applied the fix in this PR and it solved my problem.

Without the fix applied, I get a "400 The plain HTTP request was sent to HTTPS port" response (presumably from our nginx proxy). Some further digging in the output data from the axios error object, I see this url referenced: **http**://[our_proxy_host]/https://api.sandbox.cloudconvert.com/v2/jobs.

**Comment by Tchoupinax** [comment]
Hello,

Another PR was closed for the benefit of this, so i would like to know what is missing to merge it or consider to merge it ?

Thanks :)

**Comment by jasonsaayman** [comment]
I cannot see why I will add it to 0.20.0

**Comment by jonathanfoster** [comment]
@jasonsaayman I have unit tests for this fix in #3070. I also added instructions on the README to explicitly set the proxy protocol for HTTPS when configuring manually.

**Comment by jasonsaayman** [comment]
Closing in favour of #3070

**Pull request closed without merging**
