### PR TITLE
Adding tests and maxBodyLength for PUT requests (2)

### PR DESCRIPTION
**Pull request by Paxa**
This is fixed conflicts for https://github.com/axios/axios/pull/1280 by @omegaphoenix

---

Allow put requests to specify a config with maxBodyLength to override
the default (10 MB) limit on PUT requests to follow-request.

Corresponding commit and Issue in follow-request library:
follow-redirects/follow-redirects@847a47f
follow-redirects/follow-redirects#68

### CODE REVIEW

**Comment by Paxa** [comment]
btw since axios and follow-redirects use different properties for this thing, it would be nice to wrap error from follow-redirect:

Error from follow-redirects : `Request body larger than maxBodyLength limit`
Would be nice to change it to `Request body larger than maxContentLength limit`

**Comment by Paxa** [comment]
Tests failed in `should support max redirects`, not related to this PR

**Comment by Paxa** [comment]
No, but feel free to make it

**Comment by jasonsaayman** [comment]
Hi,

Thank you for this pull request, however it seem that it has gone stale and is either far out of date with the current master head or has unresolved review issues. Should you feel that this pull request is still relevant please submit a new pull request.

Thanks

**Pull request closed without merging**
