### PR TITLE
Automatic Content-Type for FormData uploads

### PR DESCRIPTION
**Pull request by nnarhinen**
When data passed to axios is of type FormData we have to let the browser
create the Content-Type header so that the boundaries will get right
etc.

Usage:

``` js
var data = new FormData();
data.append('field', 'some string');
data.append('file', someFile);

var opts = {
  transformRequest: function(data) { return data; }
};

axios.post('/fileupload', data, opts);

```

### CODE REVIEW

**Comment by powmedia** [comment]
This is working for me however the fact you need to implement a pass-through transformRequest() seems like an unnecessary step.  If the library is detecting FormData anyway could it skip the need for this requirement?

**Comment by mzabriskie** [comment]
@powmedia there was a bug #53 that was causing this to be necessary. It is no longer needed.

**Comment by dsacramone** [comment]
you don't think that is overkill to have to data.append every single form value? What if I have 20? data.append 20x seems crazy?

**Comment by ppozniak** [comment]
Necro-posting, but still wonder why that happened, as per the spec it is possible to set up custom boundary for formdata.
`Content-Type: multipart/form-data; boundary=something`
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type#Syntax

**Pull request merged**
