### PR TITLE
Feature: Fetch API Adapter

### LINKED ISSUE #1219: Feature request: fetch based adapter
I didn't see an issue for this (opened or closed), but if this is a duplicate just close it 😸 . 

Are there any plans for a `fetch` based adapter for axios? I thought I'd check and see if this has been discussed, and if not, if you all would be open to a feature request (or I'm happy to work on it and PR it). 

Reasons for adding a `fetch` adapter are basically for the same reasons you'd use fetch:
- Support for service workers
- Integration with Cache API 
- natively promise based, so axios can become a thinner library
- response streaming 
- probably more that I'm not even thinking of right now

Reasons you'd still want axios wrapping fetch for you (because some people feel like you don't need a lib over fetch): 
- fetch is low level. Using plain fetch in an app that is 99% GET/PUT/POST against a JSON API means lots of duplicate boilerplate code which axios can abstract
- request/response interceptors
- probably more that I'm not even thinking of right now :smile:

### PR DESCRIPTION
**Pull request by sgammon**
This changeset fixes and closes #1219 and addresses #2081, explained later in this PR, by adding support for the [*Fetch API*](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) via a new adapter.

CanIUse reports that [`fetch`](https://caniuse.com/#feat=fetch), having been introduced in 2014 or so (over half a decade now), is supported by roughly 95% of browsers.

Related issues:
- *React native - use fetch instead of XHR* (axios/axios#2081, filed Apr 7, 2019)
- *Feature request: fetch based adapter (axios/axios#1219)*, filed Dec 4th 2017)
- *XHR is discouraged* (axios/axios#484, filed Oct 14th 2016)
- Probably others, I don't know

Known issues:
- Upload/download progress events
  - Fetch does not have amazing support for [progress signals](https://stackoverflow.com/questions/35711724/upload-progress-indicators-for-fetch) (trigger warning: the SO article recommends Axios, which is recursively upsetting)
  - Other methodologies use [modern JS features](https://javascript.info/fetch-progress) which are banned by Axios' linter, so this is left as an exercise to the needy downstream coder
  - [This technique](https://observablehq.com/@mbostock/fetch-progress) looks good, for instance

Features so far:
- [x] Ability to `fetch` using the new adapter
- [x] Ability to enforce timeouts and cancellation signals
- [x] Error handling matching the XHR adapter
- [x] Pre-eminence in selection over the XHR adapter
- [x] Support for sending credentials
- [ ] Documentation & testing
  - [ ] Submit updates to docs where needed
  - [ ] Add tests for `fetch` specifically

### CODE REVIEW

**Comment by sgammon** [comment]
hey axios authors - this works for us in production. it makes Axios usable in a CloudFlare worker which is quite helpful when using the Contentful JS SDK (if anyone happens to find themselves here for the same issue).

getting this merged + the tests cleaned up would be super

**Comment by chinesedfan** [comment]
@sgammon Personally, I suggest you fix the test and release as an independent package. As far as I can see, axios has no plans to integrate it recently and the whole project is not active enough.

**Comment by callamwilliams** [comment]
> hey axios authors - this works for us in production. it makes Axios usable in a CloudFlare worker which is quite helpful when using the Contentful JS SDK (if anyone happens to find themselves here for the same issue).
> 
> getting this merged + the tests cleaned up would be super

Yes, please release this as its own package - we've been waiting for this functionality for a while

**Comment by hoangvvo** [comment]
Also check out [redaxios](https://github.com/developit/redaxios)

**Comment by sgammon** [comment]
i've spoken to the author of axios, best i can do my friends

**Comment by sgammon** [comment]
i'm unfamiliar with how to release this as an "add on" package to axios, i don't even know if axios has such a functionality.

if anyone has any suggestions, feel free to let me know and i'm happy to add to the PR, or contribute to another repo.

this branch works for us in prod, but we decided not to use Contentful because _both Contentful and Axios_ refused to fix this. so it's hard to allocate hours on, beyond what i've already done here, but i'm happy to help unblock people if it would be impactful.

**Comment by sgammon** [comment]
if you're here from Contentful and you're as pissed as we are that they won't fix this, [let them know](https://github.com/contentful/contentful.js/issues/395)

**Comment by softmarshmallow** [comment]
Please continue. this also resolves issue on webpack 4 removing defaults.adapter

**Comment by jasonsaayman** [comment]
Hi @sgammon,

Thanks for this contribution. For me to consider reviewing can you please remove all of the minified files? You should not be pushing anything into the `/dist` folder. Also, you have added an entirely new adapter but not added any tests to this. Please can revert the changes to the current helper test and create tests for the new fetch adapter?

Thanks

**Comment by sgammon** [comment]
@jasonsaayman no 💕

**Comment by sgammon** [comment]
@jasonsaayman does the axios team really not have the bandwidth to add tests and remove the `dist` files? we use the `dist` files because this is as yet unreleased in `npm`

or rather we did, before we switched to the contentful java SDK because of this issue.

i suppose if there is no other way, i am happy to remove the distfiles, but i would need guidance about publishing as an add-on package or contributions to help with that. i also am unfamiliar with how to load an external plugin for an axios adapter, so any guidance there would be helpful if you'd rather I finish this PR so you can write tests against it (should you need them).

**Comment by kostia-lev** [comment]
Why is it closed?

**Comment by sgammon** [comment]
@kostia-lev because the axios team wouldn't advise me about how to land this PR.

**Comment by sgammon** [comment]
@chinesedfan / @anttiviljami / @callamwilliams / @hoangvvo / @softmarshmallow / @kostia-lev 

this PR has been superseded by #5146, which adds a Fetch adapter, + support for `URL` and `Request` objects, etc. there is a new `generic` bundle you can use with Deno, Bun, and CloudFlare Workers (i.e. pure-JS environments) which ships _only_ with the fetch adapter; this allows the library to hit really small bundle sizes (only 8kb minified and compressed).

that branch has about 70% test coverage of the adapter, and it is only missing features such as cancellation, download/upload events, and so on (those are landing soon).

examples are also listed showing how to use the library in each environment. feedback is 100% welcome in order to help give it a good chance of getting merged.

**Pull request closed without merging**
