### PR TITLE
fix issue #2235: add custom `btoa` in the environment which does not support it

### PR DESCRIPTION
**Pull request by Alanscut**
### Changes:
- add custom `btoa` function for some special environment like `expo app` which does not support it
- Fix for #2235

### CODE REVIEW

**Comment by yasuf** [comment]
do you mind adding a better title and description of the PR 🙏 would make it easier in the future if we ever want info about a change

**Comment by Alanscut** [comment]
sorry, I will add more information

**Comment by danstepanov** [comment]
@yasuf Any idea on when this will be reviewed and/or merged?

**Comment by chinesedfan** [comment]
It is a revert for 5c754e6e07b536826d0a3b4e010d839482f3dd2c and e9c481fa5e49f823d35167c263465aa09feff2ca. But I think old IE support is aborted from v0.19.0-beta.1.

**Comment by Alanscut** [comment]
yeah, there is no need to support old IE in new version.

**Comment by bartzy** [comment]
Why is this closed?

**Comment by danstepanov** [comment]
This should not be close, I had to fork this for my company's use.

**Comment by agrinko** [comment]
@chinesedfan it's useful not onfly for old IE, but for non-browser environments, like React Native

**Comment by hardywu** [comment]
Please remove the `HTTP Basic auth` from the document as you removed this feature. It really cause confusion for us.

**Pull request closed without merging**
