### PR TITLE
#4412 Fix FormData detection.

### LINKED ISSUE #4412: Cannot upload file within FormData
#### Describe the bug
After upgrading from 0.24.0 to 0.25.0 File Form upload breaks.

#### To Reproduce
Original working on 0.24.0 code.
```js
axios({
    method: "post",
    url: [serverUrl],
    data: formData, // FormData object instance with uploading file field
    timeout: 120000
});
```
This code was working previously, but now backend cannot extract file field.
After specifying content type:
```js
axios({
    method: "post",
    url: [serverUrl],
    data: formData, // FormData object instance with uploading file field
    timeout: 120000,
    headers: {"Content-Type": "multipart/form-data"},
});
``` 
I got an error on backend "bad content-type header, no multipart boundary"

#### Expected behavior
Seems like previous version of axios (0.24.0) automatically add correct header and also boundary.
Or was there any breaking change that I didn't notice?

#### Environment
 - Axios Version [0.25.0]
 - Node.js Version [16.0.0]
 - Additional Library Versions [formidable 2.0.1, React-Native 0.66.4]

#### Additional context/Screenshots
Not needed.

### PR DESCRIPTION
**Pull request by Romick2005**
Closes #4412.

### CODE REVIEW

**Comment by jasonsaayman** [comment]
Closing as this has been resolved by another pull request

**Comment by danieloprado** [comment]
Can open this pull request again? There is no pull request to fix that.

**Comment by jasonsaayman** [comment]
There is please check master there is a new function that is being used to determine if something is form data

**Comment by danieloprado** [comment]
Oh! Sorry I saw the dist folder, thanks!

**Comment by jasonsaayman** [comment]
Cool I will probably do a release tonight but there are breaking changes

**Pull request closed without merging**
