### PR TITLE
Guard access to process.env

### PR DESCRIPTION
**Pull request by LinusU**
The fix described in #1922 

ping @rootsher

### CODE REVIEW

**Comment by LinusU** [comment]
Seems like Travis timed out, mind restarting it? ☺️

**Comment by 43081j** [comment]
#1689 closes this FYI

**Comment by LinusU** [comment]
Yeah, the idea with this pull request (as discussed here #1922) was to get a hotfix v0.18.1 release out ☺️

**Comment by AllainPL** [comment]
@rootsher any updates :)?

**Pull request closed without merging**
