### PR TITLE
Fixing issue for HEAD method and gziped repsonse

### LINKED ISSUE #2665: [Bug] Axios crashes on HEAD method and gziped repsonse
**To Reproduce**
Code snippet to reproduce, ideally that will work by pasting into something like https://npm.runkit.com/axios, a hosted solution, or a repository that illustrates the issue. 

```js
const axios = require("axios")

const url = 'https://stackoverflow.com/questions';

const {headers} = await axios.head(url, {
  headers: {'accept-encoding': 'gzip, deflate, br'}
});
```
You can run this in one click here https://runkit.com/embed/eocb5097ds6r
 
**Expected behavior**
Don't crush

**Environment:**
 - Node.js any version

**Solution:**
It require trivial fix similar to https://github.com/axios/axios/pull/1129

### PR DESCRIPTION
**Pull request by galkin**
This pull should fix #2665 and very similar to #1129

### CODE REVIEW

**Comment by chinesedfan** [comment]
@galkin Thanks for your fix and it looks good to me. Forgive that I am not an HTTP expert. I want to ask a question before approving. Does it mean HEAD requests will always have no content? At least, [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD) says that.

**Comment by galkin** [comment]
@chinesedfan, yes, according to http specification HEAD requests always have not body, but headers should be equals to GET method.

**Comment by chinesedfan** [comment]
@galkin Would you mind updating the branch with the latest master? Looks like your PR is based your master branch, so I can't update it by myself.

**Comment by galkin** [comment]
@chinesedfan, done.

**Comment by chinesedfan** [comment]
@galkin Damn it. I just fixed a test bug, #2748. Can I beg you again?

**Comment by galkin** [comment]
@chinesedfan, done.

**Pull request merged**
