### PR TITLE
Update tests to match new interface

### PR DESCRIPTION
**Pull request by slavovojacek**
Related to https://github.com/mzabriskie/axios/pull/496.

### CODE REVIEW

**Comment by nickuraltsev** [comment]
@slavomirvojacek Thank you for the PR! Could you please explain why this change is needed? All the request methods (`request`, `get`, `post`, etc.) would still return `AxiosPromise`, so you would need to "cast" `AxiosResponse<any>` to `AxiosResponse<DataType>`. How is that different from "casting" `data` to a specific type?

**Comment by slavomirvojacek** [comment]
@nickuraltsev No worries. Suppose an Rx stream like below:

```typescript
class ConstructWithName {
    name: string;

    constructor(name: string) {
        this.name = name.trim();
    }
}

ISomeSuccessResponse {
    name: string;
}

ISomeErrorResponse {
    message: string;
    error: boolean;
}

 return HttpProvider
    .request(ApiOperation.GetSomeResponse)
    .retry(3)
    .map((response: AxiosResponse<ISomeSuccessResponse>) => {
        return new ConstructWithName(response.data.name);
    })
    .catch((errorResponse: AxiosError<ISomeErrorResponse>) => {
        return Observable.throw(new Http.BadRequestError(errorResponse.data.message));
    });
```

I think the above would be much nicer, easier, and compact compared to something like:

```typescript
    ...
    .map((response: AxiosResponse) => {
        const data = response.data as ISomeSuccessResponse;

        return new ConstructWithName(data.name);
    })
    .catch((errorResponse: AxiosError) => {
        const error = errorResponse.data as ISomeErrorResponse;
        
        return Observable.throw(new Http.BadRequestError(error.message));
    });
    ...
```

Does it make sense or is there something I am missing?

**Comment by slavomirvojacek** [comment]
@IRus @nickuraltsev any news on the above?

**Comment by IRus** [comment]
@slavomirvojacek hi! i'm not maintainer, but this PR has conflict, so please fix this is first place. Also i found that add generic type to AxiosPromise will be useful.

**Comment by slavomirvojacek** [comment]
@IRus There should be no conflicts now and the tests should pass, any ETA on getting this in?

**Comment by rubennorte** [comment]
Please review the conflicts.

@nickuraltsev could you review this?

**Comment by Jamesking56** [comment]
@slavovojacek still showing conflicts with `index.d.ts`. Please resolve all conflicts so we can review accordingly.

**Comment by nickuraltsev** [comment]
I'm going to close this as `AxiosResponse` is a generic type now.

**Pull request closed without merging**
