### PR TITLE
fix: include config on new CancelledError

### PR DESCRIPTION
**Pull request by arthurfiorette**
Suplement of #4659 and #4711.

Another line of code that throws `CanceledError` was left behind. :)

### CODE REVIEW

**Comment by arthurfiorette** [comment]
The CI broke because of what? Do not seems an issue with the 2 parameters I added. Can someone rerun it?

**Comment by Legion2** [comment]
We are getting many errors because `config` property of AxiosError is undefined in our request interceptors, but according to the typescript definition it is not allowed to be undefined. We think that this is caused by CancelledError which do not include the config property.

**Comment by arthurfiorette** [comment]
@jasonsaayman can we get this merged? :)

**Comment by arthurfiorette** [comment]
@DigitalBrainJS can you approve this PR?

**Review by jasonsaayman — APPROVED** [review]

**Pull request merged**
