### PR TITLE
Update 'geturi' method for more information

### PR DESCRIPTION
**Pull request by Alanscut**
###  Changes:

* According to the content provided in the configuration, the method will return as much information as possible, including protocol, domain, port, path, query, etc
* Fiix for #2468 

### note: 
The hash mark will lost because it only guides the browser and has no effect on the server at all

### CODE REVIEW

**Comment by sirlantis** [comment]
Anything stopping the merge?

**Comment by utluiz** [comment]
I'd love to see this change however I'd like to point out that a better approach would be creating a new API method and deprecating the current one, rather than just changing existing behavior.

Let's say I'm using a previous version and and I have something like `baseURL + config.getUri(config)`. Now my code works but logic is broken at runtime without warning.

**Comment by jasonsaayman** [comment]
We would not be able to merge this without making a breaking change so i think for now we are going to have to leave it as is. We would like to present a v0.20.0 to the community soon that will mend all instability in Axios and then start working on features from there.

I will keep this open and maybe we can look at it in a next version after we have gain stability again.

**Comment by jasonsaayman** [comment]
Hi,

I am closing this as it is too old to reliably merge. Please open a new pull request should you want to add this functionality within the confines of the latest Axios version.

Thanks

**Comment by sakarit** [comment]
Opened a new PR #3737

**Pull request closed without merging**
