### PR TITLE
Fix ignored custom config

### PR DESCRIPTION
**Pull request by oleduc**
As described in issue #1718 as of beta-0.19 custom configuration is broken which breaks a plugin that we are using (3846masa/axios-cookiejar-support). This pull request aims to restore the behavior that was present in 0.18.0 without adding a new feature (unlike #1831)

### CODE REVIEW

**Comment by oleduc** [comment]
@emilyemorehouse I would greatly appreciate if someone could have a look at this :)

**Comment by rafaelrenanpacheco** [comment]
@emilyemorehouse hello! What's the status on this PR? Look's like there are some conflicts and the author didn't fix it so far. Will you work on this conflicts or would you like a fresh new PR regarding this fix? Lot's of axios plugins are crashing in 0.19 because the custom config was removed.

**Comment by jasonsaayman** [comment]
@oleduc please, can you remove the `dist` folder from the pull request?

**Comment by jasonsaayman** [comment]
@rafaelrenanpacheco if you want to rather put in a pull request that does not include the `dist` folder, please do so, then at me in that pull request. I can then close this one and reference to that one.

**Comment by rafaelrenanpacheco** [comment]
Hey @jasonsaayman! Here is the new PR: #2207

Thanks!

**Comment by marosivanco** [comment]
What are the plans for merging and releasing of this PR? In which version will it be released?

**Comment by rafaelrenanpacheco** [comment]
This fix was merged at #2207 

@felipewmartins I think this PR can be closed.

**Pull request closed without merging**
