### PR TITLE
fix security volunerability in follow-redirects

### PR DESCRIPTION
**Pull request by gnesher**
The current version of follow-redirects (1.15.0) is flagged with high-security risk by Snyk, this PR simply upgrades to version 1.15.4 to solve this.

### CODE REVIEW

**Review by Philip-Carneiro-KX — APPROVED** [review]

**Review by AbdelrahmanHafez — APPROVED** [review]

**Comment by jasonsaayman** [comment]
issue https://github.com/axios/axios/issues/6164

**Review by jasonsaayman — APPROVED** [review]

**Review by wjkawecki — APPROVED** [review]

**Comment by jasonsaayman** [comment]
@gnesher seems that the tests are failing, I do however believe the message may have just changed so can you just address that and I can merge?

**Comment by gnesher** [comment]
> @gnesher seems that the tests are failing, I do however believe the message may have just changed so can you just address that and I can merge?

I've pushed a fix that simply accommodates the new text, but I'd be honest and say I'm not sure where (or why) it's coming. Anyhow the test passes :)

**Review by Myszko-wr — APPROVED** [review]

**Comment by Arthuzuga** [comment]
@jasonsaayman please could you do a new review here? 😉

**Review by Philip-Carneiro-KX — APPROVED** [review]

**Comment by jabennett1515** [comment]
When can this get merged? We are currently experiencing issues and need this to be deployed in a release. @jasonsaayman @gnesher

**Review by dabrad26 — APPROVED** [review]

**Comment by mddohm1** [comment]
Nice!  Thanks @dabrad26!!

**Pull request merged**
