### PR TITLE
Update typings

### PR DESCRIPTION
**Pull request by IRus**
Updating typings. 

I used Typescript 2.x

- [x] Add generic type to both Promise and Response.
- [x] Delete typings since es6-promise package contains type definitions.

Example of usage before:

```
import axios, * as axiosTypes from 'axios';

export class RestHttpService {
  static Get<T>(path: string, config?: axiosTypes.AxiosRequestConfig): Promise<T> {
    return axios.get(path, config).then(payload => payload.data) as Promise<T>;
  };

  static Post<T>(path: string, data?: any, config?: axiosTypes.AxiosRequestConfig): Promise<T> {
    return axios.post(path, data, config).then(payload => payload.data) as Promise<T>;
  };

  static Put<T>(path: string, body?: any, config?: axiosTypes.AxiosRequestConfig): Promise<T> {
    return axios.put(path, body, config).then(payload => payload.data) as Promise<T>;
  };

  static Remove<T>(path: string, config?: axiosTypes.AxiosRequestConfig): Promise<T> {
    return axios.delete(path, config).then(payload => payload.data) as Promise<T>;
  };
}
```

Example of usage after:

```
import axios, {AxiosRequestConfig, AxiosResponse, Promise} from 'axios';

export class RestHttpService {
  static Get<T>(path: string, config?: AxiosRequestConfig): Promise<T> {
    return axios.get<T>(path, config).then(payload => payload.data);
  };

  static Post<T>(path: string, data?: any, config?: AxiosRequestConfig): Promise<AxiosResponse<T>> {
    return axios.post<T>(path, data, config);
  };

  static Put<T>(path: string, body?: any, config?: AxiosRequestConfig): Promise<T> {
    return axios.put<T>(path, body, config).then(payload => payload.data);
  };

  static Remove<T>(path: string, config?: AxiosRequestConfig): Promise<T> {
    return axios.delete<T>(path, config).then(payload => payload.data);
  };
}
```

See also https://github.com/mzabriskie/axios/pull/508

### CODE REVIEW

**Comment by basarat** [comment]
I have reviewed this and this is exactly what I was about to PR. looking forward to this getting released 🌹❤

**Comment by IRus** [comment]
@mzabriskie hi, something wrong with this PR? How can i help you to get this PR done? Happy Holidays! :)

**Comment by dpoineau** [comment]
Is there a reason that these updated Typescript definitions (and the original ones) include their own re-declaration of the `Promise<T>` type, rather than just relying on the global (or polyfilled) type existing ( https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es6.d.ts#L5261 or https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/es6-promise/index.d.ts )

This can actually cause issues because you end up with two incompatible Promise types if you directly use the global/polyfilled type elsewhere, which can cause an error like was seen here: https://github.com/mzabriskie/axios/issues/480#issuecomment-255993904

My assumption would be that there's no reason to re-declare Promise<T> at all: for example, see how the fetch API typescript definitions just assume it's available: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/whatwg-fetch/index.d.ts

**Comment by IRus** [comment]
@dpoineau i think changing `Promise` out of this PR scope

**Comment by IRus** [comment]
And since TypeScript can merge interfaces i doesn't see any problems here http://www.typescriptlang.org/docs/handbook/declaration-merging.html

**Comment by mktange** [comment]
@dpoineau That issue is fixed with this PR: #588

**Comment by Lxxyx** [comment]
Generic type for Promise is important and useful for typescript users.

**Comment by IRus** [comment]
@mzabriskie, @rubennorte, @nickuraltsev any update on this really small and usefull change?

**Comment by Lxxyx** [comment]
https://www.npmjs.com/package/@types/axios

There is an types package for axios with Generic type. It's useful and helpful for typescript users.
So anybody can update on this really small and useful change?

Or I will try to update @types/axios to newest version.

**Comment by IRus** [comment]
@Lxxyx this is always solution, but i hope maintainers will accept this PR. Two month from submitting :confused:

**Comment by Lxxyx** [comment]
@IRus Yes, I'm ready to write the definition files by myself.

**Comment by morlay** [comment]
`export default axios` should be `export = axios`

**Comment by IRus** [comment]
@morlay why? export default works well for me

**Comment by morlay** [comment]
@IRus Sorry, I miss this line code `module.exports.default = axios;`

**Comment by IRus** [comment]
@mzabriskie, @rubennorte, @nickuraltsev Hi, just want to know is there any problems with this PR

**Comment by Kuirak** [comment]
@mzabriskie, @rubennorte, @nickuraltsev can we merge and release this. It would make types so much better.

**Comment by djyde** [comment]
Any progress? cc @nickuraltsev

**Comment by nickuraltsev** [comment]
Closing in favor of #1061

**Pull request closed without merging**
