### PR TITLE
Fixing `isAxiosError` typings to take generics

### PR DESCRIPTION
**Pull request by latipun7**
I'm trying to solve this issue from #3815, this removes a workaround as stated from this https://github.com/axios/axios/issues/3815#issuecomment-951107696

Also, I make formatting changes. If you don't like it, I could drop it.

closes: #3815

### CODE REVIEW

**Comment by Guuz** [comment]
Whats the status on this?

**Comment by latipun7** [comment]
> Whats the status on this?

I don't know. I already keep this pull sync with `master` branch. Need maintainer to approve this.

**Comment by arfianadam** [comment]
This would be very useful. Bumping.

**Comment by justirva09** [comment]
waiting for this merge 👍🏻

**Comment by jasonsaayman** [comment]
This will have to go into Axios next as it will be a breaking change

**Comment by latipun7** [comment]
> This will have to go into Axios next as it will be a breaking change

@jasonsaayman sorry if I'm wrong, I don't think this is breaking change, this is just kind of new feature since old behavior still acceptable without issue. This is still good:

```ts
let user: User = null;
try {
  const { data } = await axios.get('/user?ID=12345');
  user = data.userDetails;
} catch (error) {
  if (axios.isAxiosError(error)) {
    handleAxiosError(error);
  } else {
    handleUnexpectedError(error);
  }
}
```

but accept the custom interface:

```ts
interface ResponseData {
 // ...
};

interface RequestConfigData {
 // ...
};

let user: User = null;
try {
  const { data } = await axios.get('/user?ID=12345');
  user = data.userDetails;
} catch (error) {
  if (axios.isAxiosError<ResponseData, RequestConfigData>(error)) {
    handleAxiosError(error);
  } else {
    handleUnexpectedError(error);
  }
}
```

CMIIW

**Comment by arthurfiorette** [comment]
Why this is a breaking change? All generics have a default `any` type.

**Comment by arfianadam** [comment]
@jasonsaayman what is the new error handling and how does it solve this problem?

**Comment by jasonsaayman** [comment]
I have already re-opened one of the other pull requests that deals with this.

**Pull request closed without merging**
