### PR TITLE
feat(http): enable ssl tunneling through proxy

### PR DESCRIPTION
**Pull request by Thore1954**
This is similar to #5037 but has a simpler implementation adapted from [hpagent](https://github.com/delvedor/hpagent) and additionally supports HTTPS proxies.

### CODE REVIEW

**Comment by Thore1954** [comment]
@jasonsaayman would you please take a look at this?

**Comment by robertpatrick** [comment]
any update on this?  I am running into the same issue

**Comment by Matthiasvanderhallen** [comment]
This looks like a good improvement. I just wanted to remark that it looks like this does not include the fix you provided in PR #5772  which was closed without merging?

**Comment by ShemTovYosef** [comment]
Hi @Thore1954 don’t you plan to merge it? Any workaround that you can advice ?

**Comment by Matthiasvanderhallen** [comment]
If it's not against etiquette, I'm willing to make any updates necessary to get this to a point where it can be merged.
Only if @Thore1954 is not planning to champion this further in another branch or something like that, of course...

**Comment by Thore1954** [comment]
> I just wanted to remark that it looks like this does not include the fix you provided in PR #5772 which was closed without merging?

I realized these two PRs would have merge conflicts so I decided to close it and create a new one later. Besides, the issue I pointed out is not only for proxy url auth, but also for target url auth:
https://github.com/axios/axios/blob/2701911260a1faa5cc5e1afe437121b330a3b7bb/lib/adapters/http.js#L357-L361
> Hi @Thore1954 don’t you plan to merge it? Any workaround that you can advice ?

I was indeed expecting a maintainer to merge it at one time. As for the workaround, I am currently using [this proxy server](https://github.com/Thore1954/proxy) which I modified to handle HTTPS requests without tunneling, although it should be used with caution. Alternatively, you could try patching your axios dependency using [patch-package](https://www.npmjs.com/package/patch-package).
> I'm willing to make any updates necessary to get this to a point where it can be merged. Only if @Thore1954 is not planning to champion this further in another branch

The reason I closed this PR is that it would introduce a breaking change. For the moment, it should be implemented behind a flag, but I would set it as default in the next major release since it aligns with all proxy servers.
I am presently not incentivized to pursue this further since my workaround is working adequately for the time being.

**Comment by ShemTovYosef** [comment]
Unfortunately we cannot modify the code or use additional server .
As I understood, you don’t have plans to introduce fix in the near future, maybe @Matthiasvanderhallen can continue with it?

**Comment by Suall1969** [comment]
I created #6465 which makes this a non-breaking change by introducing a new option to tunnel any request as needed.

**Pull request closed without merging**
