### PR TITLE
Release 0.19.1

### PR DESCRIPTION
**Pull request by yasuf**
### Changes
* Releases 0.19.1
* Update `dist` files so that we can have a few fixes live
* Among the fixes is the one for https://github.com/axios/axios/issues/2438 which is pretty popular and has been coming up repeatedly.

@felipewmartins @emilyemorehouse  Don't know what's the process for this? Hopefully we can have this change live on npm soon and bump the minor version at least.

### CODE REVIEW

**Comment by colebowl** [comment]
@emilyemorehouse / @yasuf - Is there any updates on this update. We are waiting for this version for the fix to #2438. Thanks!

**Comment by JeromeYangtao** [comment]
@yasuf When will the 0.19.1 version be released ? There was serveral issues similar to [#2438 ](https://github.com/axios/axios/issues/2438)

**Comment by JeroenReumkens** [comment]
Is there anything we can help with to move this PR forward?

**Comment by mrleblanc101** [comment]
Hi,
#2207 has been merged and bring fixes for #2006, #2203 which are needed in other plugin like
nuxt-community/axios-module#258

**Comment by yasuf** [comment]
Hey @mrleblanc101 @JeroenReumkens, thanks for your patience, Emily just confirmed she will get this merged and released in a couple of weeks

**Comment by mrleblanc101** [comment]
v0.19.0 was released all the way back in may with breaking change. Why does it take 6 months with no news to get a "couple weeks" timeframe just to release a bug fix ?

**Comment by matushorvath** [comment]
We are also waiting for this release because of the breaking change related to custom properties on config.

**Comment by heisian** [comment]
you all will have a better time forking the project - this is a not-very-well maintained (but widely-used) package. Expect the process to take months.

**Comment by mrleblanc101** [comment]
Sadly I do not use axios/axios, I use @nuxtjs/axios so I would need to fork and maintain both dependency.

**Comment by heisian** [comment]
would recommend forking your own and maintaining your own

**Comment by n-sviridenko** [comment]
Any updates on this? What forks do you guys use?

**Comment by EthianWong** [comment]
i'm waitting for this.

**Comment by EthianWong** [comment]
i'm waitting for this.

**Comment by Tidyzq** [comment]
looking forward to see this PR merged

**Comment by 01taylop** [comment]
I just forked and released this and it fixed our issues. All tests here pass, as well as our own so hopefully, 19.1 can be released soon.

**Comment by glebmikulko** [comment]
:eye: :eye: 
@yasuf is there an approximate date of release?

**Comment by EthianWong** [comment]
i'm waitting for this.

**Comment by yasuf** [comment]
In the meantime I've published my fork of this library at https://www.npmjs.com/package/community-axios
It's the exact same library, just the package name is `community-axios` just so you can use 0.19.1,  that's the best I can do for the moment, let me know what you guys think. This is since the folks who have access to npm haven't been able to publish the new version, we still need them to publish 0.19.1 on this main repo since it's the one everybody uses.

**Comment by iangregsondev** [comment]
@yasuf Great, do you know of any way to force all dependents to use this version instead of Axios?

If it was version change then we could edit the package-lock.json file but it's not, it's a different package (although the same :-) ).

I have libraries that are installed that need Axios and those libraries don't belong to me (installed via npm) - so if there is no way of overriding it (or redirecting it) - this isn't usable for me.

Does anyone know a way around this?

**Comment by mrmartineau** [comment]
@yasuf thanks for publishing your version of the package, but I am confused as to why axios itself has not been published. Can you or another contributor explain? Are there any tasks still outstanding before 0.19.1 can be released?

**Comment by emilyemorehouse** [comment]
0.19.1 is published!

@yasuf I pulled your CHANGELOG updates and rebuilt off of master to let the release automation do it's thing. Thanks for your help!

**Comment by heisian** [comment]
> @yasuf Great, do you know of any way to force all dependents to use this version instead of Axios?
> 
> If it was version change then we could edit the package-lock.json file but it's not, it's a different package (although the same :-) ).
> 
> I have libraries that are installed that need Axios and those libraries don't belong to me (installed via npm) - so if there is no way of overriding it (or redirecting it) - this isn't usable for me.
> 
> Does anyone know a way around this?

If such a mechanism existed, it could be used maliciously, i.e. one could force all "dependents" to use a different version of the package containing malware.

**Comment by iangregsondev** [comment]
exactly, which is why I doubt there was - but no harm is asking :-)

Anyway - it's now been released, and finally able to have a custom config again.

Thanks

**Pull request closed without merging**
