### PR TITLE
fix: change findKey function to use hasOwnProperty

### PR DESCRIPTION
**Pull request by eternityduck**
Improve findKey function

### CODE REVIEW

**Comment by DigitalBrainJS** [comment]
This is a completely different logic, not equal to the existing one. Also, `Object.hasOwnProperty(obj, key)` is not a valid method call.

**Comment by eternityduck** [comment]
@DigitalBrainJS in that case we can consider something like this
```
function findKey(obj, targetKey) {
  const normalizedTargetKey = targetKey.toLowerCase();
  return Object.keys(obj).find(key => key.toLowerCase() === normalizedTargetKey) || null;
}
```
I think it is will be better, logic is the same

**Comment by DigitalBrainJS** [comment]
This is equivalent but will result in decreased performance. You cannot iterate faster than using a plain reverse loop so it’s unlikely that anything better can be done here for performance reasons. ¯\_(ツ)_/¯

**Comment by eternityduck** [comment]
Seems like indeed it is, sorry for your time @DigitalBrainJS, thanks for the answers

**Pull request closed without merging**
