### PR TITLE
Expand Headers types

### PR DESCRIPTION
**Pull request by bfaulk96**
Update headers type for a request to allow `boolean` and `number` types in addition to strings.
Export `RequestHeaders` and `ResponseHeaders` type aliases

### CODE REVIEW

**Comment by bfaulk96** [comment]
This update to require `Record<string, string>` broke backwards compatibility – booleans and numbers all `toString()` cleanly, so it makes this library a lot more user-friendly to accept other primitive types

**Comment by bfaulk96** [comment]
@remcohaszing I can agree with that overall, makes sense. I guess my pain point is that this can be seen as a regression for any applications that were already using it in that way – If an app previously passed `"Access-Control-Max-Age": 5` into Axios when the type was any, the `0.22.0` update now shows a TS error instead of converting it to a string for the user.

**Comment by remcohaszing** [comment]
> I thought about this and think it would make sense to also allow `boolean` and `number` values, but not `undefined`. My guess is that `boolean`s will be converted to `"0"` or `"1"` and `number`s accordingly, even if not by axios itself. But true, that would need to be tested.

Values are  simply cast to string. `true` becomes `'true'`, `false` becomes `'false'`, objects become `'[Object object]'`, etc.

I think the axios maintainers should determine what values they want to support and the types should reflect this.

**Comment by bfaulk96** [comment]
> I thought about this and think it would make sense to also allow boolean and number values, but not undefined. My guess is that booleans will be converted to "0" or "1" and numbers accordingly, even if not by axios itself. But true, that would need to be tested.

Agreed. I got a little carried away with `undefined`, as that doesn't `toString()` nicely.

To answer the other question, yes:
`5` -> `"5"`
`true` -> `"true"`

Those seem fairly harmless to allow – but I surely understand if not.

On the note of perhaps a a feature request – would be cool to allow `Date` but would require a transformer, as HTTP date headers are different format than date's toString so it would actually need a transformer. Would be nice though :D

**Comment by bfaulk96** [comment]
Merged in latest changes 👍

**Comment by bfaulk96** [comment]
@jasonsaayman any thoughts on this?

**Comment by bfaulk96** [comment]
@jasonsaayman Any chance of getting this merged?

**Comment by bfaulk96** [comment]
bump

**Comment by jasonsaayman** [comment]
Yip will merge today

**Comment by estarossa0** [comment]
shouldn't this changes be added to response headers as well ?

**Comment by bfaulk96** [comment]
> shouldn't this changes be added to response headers as well ?

No, since HTTP Headers are always sent as strings, Response headers will be strings that you will need to parse if you want different types from them

**Comment by estarossa0** [comment]
> @jasonsaayman Any estimate on when the next Axios release might be?

https://github.com/axios/axios/pull/4379#issuecomment-1012310407

**Pull request merged**
