### PR TITLE
Fixing IE11/Edge doesn't respect responseType, so do it manually

### PR DESCRIPTION
**Pull request by Niandalu**
## Failing case

```
axios({
  url: 'example.com',
  responseType: 'json',
  transformResponse: [
    data => {
      console.log(data.message.field);  // ERROR
    }
  ]
})
```

While running the above case in IE 11, an error will be thrown at the line marked.

Because:

1. `defaults.transformResponse` gets overrided
2. IE 11 ignores `XHR.responseType` and `XHR.response` will always give out `string`

## How does this PR do

Whenever we find `responseType` is set to `json` and response type is `string`,
try to `JSON.parse` it.

### CODE REVIEW

**Comment by RikkiGibson** [comment]
Seems [Edge doesn't automatically parse JSON either](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseType#Browser_compatibility)--are you able to validate that this PR fixes that too?

The only thing that seems off to me about this is that strings are valid JSON values. So if the JSON value you got back was just a string this might try to double parse it and cause problems.

```js
> JSON.parse('"foo"')
< "foo"
> JSON.parse(JSON.parse('"foo"'))
< SyntaxError: JSON Parse error: Unexpected identifier "foo"
```

**Comment by Niandalu** [comment]
Thanks for reminding. I haven't noticed that Edge have the same issue. I'll give it a try when I got time.

As for your `JSON.parse("string")` concern, it should be fine, since the `JSON.parse` gets wrapped with `try ... catch` just like what the original `transformResponse` did.

**Comment by RikkiGibson** [comment]
Yeah, thinking on it a bit, it seems very, very niche for any ill effects to result from this.

Specifically, you'd need a response body which is decodable as a JSON string, which is itself decodable as JSON:

```js
> var weird = '"{\\"name\\": \\"strange\\"}"';
> JSON.parse(JSON.parse(weird))
< {name: "strange"}
```

Anyone who somehow encounters this can just set `responseType: text` and be in full control of it anyway.

**Comment by Niandalu** [comment]
@RikkiGibson Edge seems working fine with `responseType`. I've tested upon [the latest Edge vm](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/).

The result doesn't match what described in [the browser compatibility table](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseType)... Maybe the table is describing some legacy version of Edge.

**Comment by karolgorecki** [comment]
I'm experiencing the same issue on IE11. This change seems to fix this problem. Can we merge it?

**Comment by sunnyvempati** [comment]
soooo, are we merging this?

**Comment by chinesedfan** [comment]
> defaults.transformResponse gets overrided

If without overriding, is there still some problems? So I think the key point is setting transformResponse correctly. Remind me if I missed something.

**Pull request closed without merging**
