### PR TITLE
Default params serialisation violates RFC 3986 less.

### LINKED ISSUE #1727: Default params serialisation behaviour incompatible with recent Tomcat versions.
#### Summary

Given the default params serialisation behaviour, axios out-of-the-box may fail to work with recent Tomcat versions out-of-the-box.

The problem is the way params are serialised in the absence of a custom params serialiser configuration. The code is using the built-in `encodeURIComponent` function (good), but then proceeds to deliberately de-encode some characters. In particular, it de-encodes `[` and `]` back to raw (problem).

This is a problem with Tomcat because recent versions (_e.g._ 8.5.31+) have started being more pedantic about URI syntax, and by default will reject requests that contain `[` or `]` in the query portion.

I appreciate the motive of making the URLs built by axios more human readable, and not percent-encoding characters if you can get away with it. But blatant and wilful violation of RFC 3986, even if common practice for historical reasons, is a problem with servers that are adopting strict-by-default behaviour.

#### Context

- axios version: v0.18.0
- Tomcat 8.5.32

### PR DESCRIPTION
**Pull request by matthewlowry**
Fixes #1727.

Does so in the "standards compliant weenie" fashion, by making axios' default behaviour violate RFC 3986 less.

I appreciate that including `[` and `]` characters raw in the query portion of a request URL is a near-universal practice, but it is a clear and wilful violation of URI syntax. This makes axios' default behaviour brittle in the face of an environment were popular server implementations are getting more pedantic. And here we are with axios out-of-the-box generating requests that Tomcat out-of-the-box rejects as syntactically invalid.

### CODE REVIEW

**Comment by emilyemorehouse** [comment]
Hi @matthewlowry, thanks for the PR!

Give me a couple of days to work through this. I just went back and looked at other encoding issues (which now have their own label!) and want to make sure this is the best choice, especially considering backwards compatibility for all users.

I think it would be awesome to add a config option to enforce RFC3986 or not, so that both use cases are handled.

(also applies to #1671, and some other related issues/prs tagged 'encoding')

**Comment by matthewlowry** [comment]
> I think it would be awesome to add a config option to enforce RFC3986 or not, so that both use cases are handled.

Totally. This PR is basically just the quick and dirty hack I did to get my companies app working again. If I get some free time I'll try to whip up something better up.

**Comment by cinatic** [comment]
Hi,

what is the status here? IMO the encoding of the "key" is just wrong 

https://github.com/axios/axios/blob/81eaa3db4cf51bd911f98de5aa1ad130b3c55c8e/lib/helpers/buildURL.js#L54

**Comment by ABWalters** [comment]
Hi,

What work is still required for this PR to be merged?

I am currently unable to use this library at work as we need to have a param value containing square brackets `[]`. Our tomcat server rejects the request because the correct encoding of the characters is removed.

If I submit a PR with a config option to enable/disable RFC3986 compliance, would it be easier to merge

**Comment by jasonsaayman** [comment]
On this I don't think this should be implement as mentioned previously if you'd like to use another format, you can set a custom paramsSerializer as follows:

```js
axios.defaults.paramsSerializer: function(params) {
  // return a query string
}
```

Using the qs library:
```js
axios.defaults.paramsSerializer: function(params) {
  return qs.stringify(params, { indices: false }); // param=value1&param=value2
}
```

**Pull request closed without merging**
