### PR TITLE
Adjust karma to use Webpack 3 config

### PR DESCRIPTION
**Pull request by zcei**
Umbrella: #1333 

This PR adjust the Karma spec runner to use the same Webpack config that is used for production builds.

There is no need to have the webpack dev server running - when it was still included the bundle was emitted multiple times, without we get a single bundle that the test suite is run against.

### CODE REVIEW

**Comment by axe312ger** [comment]
Sauce Labs Result:
```
IE 11.0.0 (Windows 8.1 0.0.0): Executed 178 of 178 (93 FAILED) (0.834 secs / 0 secs)
IE 9.0.0 (Windows 7 0.0.0): Executed 178 of 178 (90 FAILED) (1.1 secs / 0 secs)
Firefox 58.0.0 (Windows 7 0.0.0): Executed 178 of 178 (93 FAILED) (0.48 secs / 0 secs)
Safari 9.1.2 (Mac OS X 10.11.6): Executed 178 of 178 (93 FAILED) (0.474 secs / 0 secs)
Edge 16.16299.0 (Windows 10 0.0.0): Executed 178 of 178 (93 FAILED) (0.676 secs / 0 secs)
Chrome 64.0.3282 (Windows 7 0.0.0): Executed 178 of 178 (93 FAILED) (0.47 secs / 0 secs)
IE 10.0.0 (Windows 8 0.0.0): Executed 178 of 178 (93 FAILED) (1.057 secs / 0 secs)
TOTAL: 648 FAILED, 598 SUCCESS
```

Looks like it does what it should. Fixing the tests itself is another PR, I guess @zcei?

**Comment by axe312ger** [comment]
IMHO this PR could also get rid of grunt, it is only used for testing (this pr + #1336), building (already rewritten and merged to release/1.0.0) and for bundeling to bower (which should get removed IMHO, bower is obsolete)

I am also happy to do this in a separate PR, would be a pleasure to simplify the build process further :)

See here:
```
  grunt.registerTask('test', 'Run the jasmine and nodeunit tests', ['eslint', 'nodeunit', 'karma:single', 'ts']);
  grunt.registerTask('build', 'Run webpack and bundle the source', ['clean', 'webpack']);
  grunt.registerTask('version', 'Sync version info for a release', ['usebanner', 'package2bower']);
```

**Comment by zcei** [comment]
Sure, I just kept that for visibility. As we currently have no replacement for `usebanner` & `coverage`.

At least something for coverage would be nice in mid-term. But probably CodeCov instead of CoverAlls?
Then I'd be fine with just getting rid of everything now and introduce proper new tooling later.

**Comment by zcei** [comment]
> Fixing the tests itself is another PR, I guess @zcei?

Next PR is adjusting the tests itselfs (removing some tests that will be obsolete, requiring instead of globals, etc)

In "TDD" approach the tests will get fixed by the PRs to come.

**Comment by axe312ger** [comment]
regarding banner: i guess we can just remov eit
regarding coverage: true, https://github.com/karma-runner/karma-coverage should help, but that maybe should be another PR, too.

**Pull request merged**
