### PR TITLE
Fixing slow maxContentLength check

### PR DESCRIPTION
**Pull request by akhilstanis**
Refines the logic to calculate the total size of the chunks received. The current logic uses a `Buffer.concat` call which could get expensive as the number of chunks gets larger.

The issue and the root cause is well described here #2829

Here are the benchmarks before and after the fix.
Before
```
withMaxContentLength => Success in 10 seconds.
withoutMaxContentLength => Success in 0 seconds.
```
After
```
withMaxContentLength => Success in 1 seconds.
withoutMaxContentLength => Success in 0 seconds.
```

### CODE REVIEW

**Comment by nomcopter** [comment]
Any estimate for timing for a merge here @chinesedfan? This issue is slowing things down for many of our requests.

**Comment by nomcopter** [comment]
Definitely not stale. Issue persists.

**Comment by tsachis** [comment]
@chinesedfan any plans to merge this one? we're facing the same issue.

**Comment by jasonsaayman** [comment]
Seems this has been solved in the lates master release. Please re-open should you feel this is a issue that must be addressed.

**Pull request closed without merging**
