### PR TITLE
Add types for AxiosError.from-method

### PR DESCRIPTION
**Pull request by phloose**
Adds the method signature for the static method `AxiosError.from` (https://github.com/axios/axios/blob/v0.x/lib/core/AxiosError.js#L79). 

Is there a reason it was not exposed so far?

I am not sure which base branch to choose :thinking:. As `AxiosError.from` is also present in the latest 0.x versions would it make more sense to make it the base branch or even main?

### CODE REVIEW

**Comment by phloose** [comment]
Sorry, but i don't get your branching strategy :sweat_smile: Why all theses conflicts? What is the base branch?

**Comment by jasonsaayman** [comment]
The base branch is no v1.x, can you please check the conflicts then I will have a look

**Comment by phloose** [comment]
Will do. I dont get why there are so many conflicts for files i didnt touch at all... :man_shrugging:

**Comment by phloose** [comment]
@jasonsaayman conflicts are fixed.

**Pull request merged**
