### PR TITLE
Remove file: protocol check when response status is 0

### PR DESCRIPTION
**Pull request by geoffdutton**
Fix for #945.

Edit: I've removed the check for the `file:` protocol. If `response.status` is 0, but the `responseURL` is truthy, it's considered okay.

~~I've added two tests:~~
~~1. A test for the `file:` protocol, as that wasn't there~~
~~2. A similar test for the `safari-extension:` protocol~~

~~I've also fixed a few ESLint errors.~~

### CODE REVIEW

**Comment by rubennorte** [comment]
We don't officially support Safari Extensions and I'm afraid that using that code in Axios core would imply that we do (potentially opening more issues we aren't capable of taking care at the moment). I see that jQuery just checks for the `0` status code, so maybe it's safe to remove the `file:` restriction. See https://github.com/jquery/jquery/blob/d2a380759f17abd54bb7576c6a1b40e2f069c3f3/src/ajax/xhr.js#L93
 
On the other hand, I don't know what ESLint configuration you've been using but most of those weren't errors. Please revert the code so only the relevant changes are applied.

**Comment by geoffdutton** [comment]
Okay I've removed the `file:` protocol restriction. 

Regarding the lint errors, if I run `grunt test`, I see this:
image

**Comment by geoffdutton** [comment]
Shoot, I reverted the test as well. I'll update shortly.

**Comment by robaxelsen** [comment]
Closing this, due to reasons stated by @rubennorte [above.](https://github.com/axios/axios/pull/947#issuecomment-322052904)

**Pull request closed without merging**
