### PR TITLE
Refactored module exports;

### LINKED ISSUE #5011: [1.0.0] TypeError: Cannot read properties of undefined (reading 'create')
#### Describe the bug

```
const client = axios.create()
                     ^

TypeError: Cannot read properties of undefined (reading 'create')
    at Object.<anonymous> (/Users/rob/Developer/Personal/full-feed/test.js:5:22)
    at Module._compile (node:internal/modules/cjs/loader:1149:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1203:10)
    at Module.load (node:internal/modules/cjs/loader:1027:32)
    at Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.10.0
```

#### To Reproduce

```js
#!/usr/bin/env node

const axios = require('axios').default

const client = axios.create()
  ```

#### Expected behavior
Runs without error.

#### Environment
 - Axios 1.0.0
 - Node.js 18.10.0
 - macOS Monterey 12.6

#### Additional context/Screenshots
* 0.27.2: runs without error
* 1.0.0: `TypeError: Cannot read properties of undefined (reading 'create')`

(I could not see any breaking change)

### LINKED ISSUE #5031: Exported classes in type definition are not actually exported
#### Describe the bug
`AxiosHeaders`, `AxiosError`, `CanceledError`  and `Axios` are "exported" in the type definitions `index.d.ts`, but not exported in the module.

#### To Reproduce

```ts
const { AxiosHeaders } = require('axios');  // Allowed by Typescript

const headers = new AxiosHeaders({ 'name': 'value' }); // <-- throws Error as AxiosHeaders is not actually exported
```

#### Expected behavior

~~Types are not exported, but only declared (`declare class` instead of `export class`).~~

Classes are exported and can be imported and used like so:
```ts
import { AxiosError, AxiosHeaders, Axios, CanceledError } from 'axios';

new AxiosError();
new AxiosHeaders();
new Axios();
new CanceledError();
```

#### Environment
 - Axios Version 1.1.0
 - Node.js Version 16.15.1
 - OS: OSX 12.5
 - Typescript 4.6.3 (any version)
 - React 17

#### Additional context/Screenshots
none

### LINKED ISSUE #5044: 🐛 [BUG] - TypeError: axios.defaults is undefined in v 1.1.0
## Description

I use CDN with `https://unpkg.com/axios/dist/axios.min.js` without specify version in my project, and before new version release, I can work it well.
But after new version release, it will show the error:

```
TypeError: axios.defaults is undefined
```

I tried to find some release notes or upgrade guide but I saw someone find them too, so I rollback to old version, and it works now!
But I have several pages needs to rollback the version 😢 

Is rollback version only way to fix this error?

## Code

I used axios with Vue.js, and this is the part in my Vue app:

```javascript
getProjectSec: function (token) {
    axios.defaults.headers.common['Authorization'] = 'Bearer ' + token;
    // ^^^^^ Uncaught (in promise) TypeError: axios.defaults is undefined

    this.projects(project => {
        axios({
            url: `api/Project/${project.value}`,
            method: 'get',
        }).then(res => {
            // Do something
        }).catch(err => {
            console.log(err.response);
        })
    })
}
```

### LINKED ISSUE #5082: Typescript imports not working
I am importing axios as follows into my typescript project:
```
import axios from 'axios';
```
which compiles without a problem, however the resulting javascript code throws an exception.
image
If I change my import to:
```
import * as axios from 'axios';
```
I get a compiler error:
image
But at least the resulting javascript code runs without issues.

Seems like there's kind of a mismatch here.

### LINKED ISSUE #5091: require not supported after upgrading to axios 1.1.2
we are getting below error after upgrading axios to the 1.1.2 version

2022-10-11T04:56:57.575682812Z stderr F Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /app/node_modules/axios/package.json.
--
  |   | 2022-10-11T04:56:57.575671912Z stderr F require() of /app/node_modules/axios/index.js from /app/server.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
  |   | 2022-10-11T04:56:57.575663912Z stderr F require() of ES modules is not supported.
  |   | 2022-10-11T04:56:57.575654512Z stderr F Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /app/node_modules/axios/index.js
  |   | 2022-10-11T04:56:57.575647612Z stderr F
  |   | 2022-10-11T04:56:57.575640211Z stderr F       ^
  |   | 2022-10-11T04:56:57.575628111Z stderr F       throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
  |   | 2022-10-11T04:56:57.575556611Z stderr F internal/modules/cjs/loader.js:1172

 - Axios Version 1.1.2

 - Node.js Version 12

### LINKED ISSUE #5118: After upgrading form v0.27.2 to v1.1.2 import error with Vite
#### Summary

In Vue3 / TypeScript project,
import { AxiosError } from 'axios';

Build shows warning:
Non-existent export 'AxiosError' is imported from node_modules/axios/index.js

Although there is only a build warning, any component (Vue) or TypeScript (ts) that includes this import fails to work.
Browser console (Dev-Tools) shows:

Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/axios.js?v=3226fa61' does not provide an export named 'AxiosError' (at auth-store.ts:2:17)

#### Environment
 - Axios Version 1.1.2
 - Node.js Version v17.4.0
 - OS: Windows 10
 - Vite version: 3.1.7

### LINKED ISSUE #5130: `1.1.3` probably broken
### Describe the bug

I think there are issues is exporting the axios object and also a issue when in get function when in the instance of Axios class.

### To Reproduce

Install
- Axios `V1.1.3`
- Node `v18.4.0`

### Code snippet

```js
const { Axios, default: a } = require('axios');

const ax = new Axios();

a.get("https://www.eldorado.gg/buy-wow-gold/g/0-0-0").then(x => console.log(x.data))

ax.get("https://www.eldorado.gg/buy-wow-gold/g/0-0-0").then(x => console.log(x.data))
```

### Expected behavior

This code should have logged the data (html) from that url.
Mainly the issue is that default export is undefined.

### Axios Version

`>1.1.0`

### Adapter Version

_No response_

### Browser

_No response_

### Browser Version

_No response_

### Node.js Version

18.4.0

### OS

Windows 10

### Additional Library Versions

_No response_

### Additional context/Screenshots

```bash
There were bugs like
1. In default export, that is undefined. [Image](https://media.discordapp.net/attachments/723104565708324915/1031017046743461928/unknown.png)

2. `Axios`'s instance's get function have a bug as well. [Image](https://media.discordapp.net/attachments/723104565708324915/1031017137382363336/unknown.png)

I tested old versions and for me version `1.1.0` and earlier versions are working fine.
```

### LINKED ISSUE #5154: axios 1.1.3 can't use in a library
### Describe the issue

Hi, i've created a library and it was working fine, but after the update to 1.1.3 it started to give me a bunch of the following error :
"BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
        - install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "stream": false }","

I'm currently using 1.1.2 and it's working fine, but since i'm not the only one that uses the library, i'm afraid of this issue, how can i fix this? i already tried to upgraded the version of both(library and project) to 1.1.3 and doesn't work, the only thing that worked for me until now was setting everything back to 1.1.2. Help!
 

### Example Code

_No response_

### Expected behavior

_No response_

### Axios Version

1.1.3

### Adapter Version

_No response_

### Browser

_No response_

### Browser Version

_No response_

### Node.js Version

_No response_

### OS

_No response_

### Additional Library Versions

```bash
angular 14.0.0
```

### Additional context/Screenshots

_No response_

### LINKED ISSUE #5164: ESLint no-named-as-default-member for isAxiosError
### Describe the bug

After upgrade to 1.1.3 my ESLint complains about `import/no-named-as-default-member`

image

But in reality, I cannot import as `import { isAxiosError } from 'axios';`

image

So something is broken with TS types

### To Reproduce

Turn on `import/no-named-as-default-member` ESLint rule, update axios to 1.1.3, try to use `axios.isAxiosError` and observe error.

### Code snippet

_No response_

### Expected behavior

I should be able to satisfy eslint and be able to import as `import { isAxiosError } from 'axios';`

### Axios Version

1.1.3

### Adapter Version

_No response_

### Browser

_No response_

### Browser Version

_No response_

### Node.js Version

_No response_

### OS

_No response_

### Additional Library Versions

```bash
xo 0.52.4
```

### Additional context/Screenshots

_No response_

### PR DESCRIPTION
**Pull request by DigitalBrainJS**
Brief description:
- `require` can only be used with `default` export as it was in 0.x versions;
- `import` can be used with both `default` & `named` exports;

Detailed:
- Added browser CommonJS bundle to the build pipeline;
- Fixed exports entry points;
- Added module exports tests;
- Added missing ESM export for parity with Axios factory; 
- Added `toFormData`, `formToJSON`, `isAxiosError`, `spread`, `isCancel`, `all` as named export to `index.d.ts`;

In an attempt to bring order, the package export has been refactored. The following rules were adopted:
- CommonJS module has only factory as default export, as it was before
- CommonJS entry point to build the cjs bundle is `./lib/axios.js`
- ESM entry provides both default (factory) and named exports;
- ESM entry point is `./index.js`. This module should expand Axios factory export as ESM named export. This module should not be used for purposes other than re-export features as a named export.
- Named export should be in parity with export provided by Axios factory
- The `./dist/axios.js` and `./dist/esm/axios.js` bundles are for CDN usage only.

Closes #5154; Closes #5164; Closes #5169; Closes #5091; Closes #5130; Closes #5118; Closes #5011; Closes #5031; Closes #5044; Closes #5082;
Related: #5101, #5026, #5088

Users that import the module with `require` will do it as it was before:

```js
const axios = require('axios');

console.log(axios.isCancel('something'));
console.log(new axios.AxiosError('oops'));
```
If the module is loaded with `import` statement you can use both named and factory exports:

```js
import axios from 'axios';

console.log(axios.isCancel('something'));
console.log(new axios.AxiosError('oops'));
```
OR
```js
import axios, {isCancel, AxiosError} from 'axios';

console.log(isCancel('something'));
console.log(new AxiosError('oops'));
```
If something goes wrong (custom/outdated environment), you can try to load CommonJS bundle directly:
```js
const axios = require('axios/dist/browser/axios.cjs'); // browser
// const axios = require('axios/dist/node/axios.cjs'); // node

console.log(axios.isCancel('something'));
console.log(new axios.AxiosError('oops'));
```

### CODE REVIEW

**Comment by KrayzeeKev** [comment]
What is the process for these getting released? Is there a regular release cadence? Or is it waiting for some magic? Or does it happen manually when there's enough to warrant a release?

**Comment by DigitalBrainJS** [comment]
@jasonsaayman Can we have a pre-release with this PR like 1.2.0-beta.1? It would be nice to get early user feedback on this. In case when exports are broken a separate release/pre-release is desirable to avoid implicit collisions with other PRs that change the export in some way.

**Comment by jasonsaayman** [comment]
@KrayzeeKev no there is no set schedule. I would like to implement something like that but it is pretty hard as I also have work to attend too. I will look into doing something like a monthly schedule. @DigitalBrainJS yeah sure, the only problem is it will get very little traction, for the entire time we pre-released v1 we got 3000 downloads, pretty sure about 200 were my own projects.

**Comment by jasonsaayman** [comment]
But yeah I will cut it as mentioned this weekend.

**Comment by KrayzeeKev** [comment]
@jasonsaayman Thx. I'm with you on the whole pre-release thing. We can't use them. It's `npm update` or nothing for us. I'd happily try one on my local for you but the fundamental problem we have here is we're running 0.27 because nothing above 1.0 works (axios-retry and nock in our ecosystem) And my security people are looking at that ^0 and not liking me :-)  I might see if I can contort firewalls and proxies sufficiently to test the latest github branch on this but I've failed to achieve that in the past. The world really wants me to use npm versions (internal npm cache, no direct internet, etc, etc)

**Comment by KrayzeeKev** [comment]
I've managed to pull this version in using https but our code has always used: require('axios').default; 
I don't know why. It was like that when I got it. Now it breaks. Is that the result of this PR or some other 1.x change? Does require('axios') give us now exactly what .default gave us before?

**Comment by DigitalBrainJS** [comment]
@KrayzeeKev They are equivalent: 
```js
module.exports = axios;
module.exports.default = axios;
```
Just re-added support for this for backward compatibility in #5225 .

**Comment by KrayzeeKev** [comment]
@DigitalBrainJS Thanks. Easy to fix on our end too. Now I have to go back through the tickets that this merge is supposed to fix so I can tell everybody which ones it doesn't (axios-retry still broken with a function body in an http header)

**Pull request merged**
