### PR TITLE
Fixing issue 2195

### LINKED ISSUE #2195: 0.19.0 no longer works with xhr-mock
**Describe the bug**
Running Jest unit tests with xhr-mock https://github.com/jameslnewell/xhr-mock fail. Reverting to 0.18.0 fixed it.

### PR DESCRIPTION
**Pull request by masterots**
Fixes #2195 

The order of the if/else blocks matters when running tests mocking XHR. Changing the order allows this to continue working in node and browsers, but also allows for unit tests to properly connect over the correct protocol.

### CODE REVIEW

**Comment by jmelvin-r7** [comment]
@emilyemorehouse would it be possible to get an ETA for when this could be merged? I'd like to update my team/management on the fix for this issue.

**Comment by jmelvin-r7** [comment]
Is anyone able to merge changes other than @emilyemorehouse? This is becoming a hindrance to us continuing to use this library, if we can't get timely responses to get fixes handled.

**Comment by jasonsaayman** [comment]
@jmelvin-r7, unfortunately, I think its only Emily and the three other original maintainers at this time.

**Comment by hendrikskevin** [comment]
@emilyemorehouse @mzabriskie @nickuraltsev @rubennorte Going to tag all of you. This issue is really becoming a bother and a forced downgrade to 0.18.0 is the only way to prevent it, but if this PR can be merged and a new release (0.19.1?) be made that would be great.

**Comment by akirilyuk** [comment]
@jasonsaayman hey this does not work for node, since i am also getting xhr when executing axios on node.js...

**Comment by akirilyuk** [comment]
Screenshot 2020-02-11 at 10 00 49

**Comment by jasonsaayman** [comment]
@akirilyuk I will have a look thanks

**Pull request merged**
