### PR TITLE
Added getUri method

### PR DESCRIPTION
**Pull request by delirius325**
This is a new feature to get the built URI of an axios instance. It's been added in regards to this issue https://github.com/axios/axios/issues/1624 , I thought the use-case was interesting and I didn't think it was a good idea to include this feature in a third-party module. 

This code 
```javascript
const axios = require('axios');
const fakeConfig = {
  method: 'post',
  url: '/user/12345',
  data: {
    firstName: 'Fred',
    lastName: 'Flintstone'
  },
  params: {
    idClient: 1,
    idTest: 2,
    testString: 'thisIsATest'
  }
}
console.log(axios.getUri(fakeConfig));
```
Outputs
```bash
/user/12345?idClient=1&idTest=2&testString=thisIsATest
```

### CODE REVIEW

**Comment by delirius325** [comment]
@atrauzzi 

Yup! Because this line

```javascript
config = mergeConfig(this.defaults, config);
```

Takes the default configs and merge them with the specified config. Therefore you could call ```.getUri()```without any parameters and it should return the already configured values.

Cheers 😄,

**Comment by delirius325** [comment]
Yeah, it was crazy simple.. I had the solution Friday before closing my laptop and when I opened it up this morning I was like : "Well, could've committed that Friday 😅 ". 

Now just gotta wait for someone to approve the change and merge it to axios 🤞 !

**Comment by delirius325** [comment]
@emilyemorehouse Done 😄

**Comment by martin-yin** [comment]
Wow, look what I found.Can you add getUri to the introduction?  
Because when I read the source code, I saw this method, and at first I wondered what he was doing.
And I didn't see his code example in markdown. So I hope you can add his code example in markdown

image

**Comment by delirius325** [comment]
Hi @martin-yin! I welcome you to contribute to the documentation and add the example 😄 !

**Pull request merged**
