### PR TITLE
Bug/allow header to contain http verb keys #1252

### PR DESCRIPTION
**Pull request by nycdavid**
This PR fixes bug #1252 where HTTP headers whose keys match some HTTP verb are deleted from the headers object.

The fix changes the `cleanHeaderConfig` function to only delete the key if it's value is a non-string.

### CODE REVIEW

**Comment by jcrben** [comment]
LGTM - in general, we shouldn't have to mess with removing headers - the user agent (browser) can handle [rejecting forbidden headers](https://fetch.spec.whatwg.org/#forbidden-header-name)

**Comment by zcei** [comment]
@jcrben btw Axios is using `XMLHttpRequest`, but still the user agent can reject headers there.
As your link states correctly, HTTP verbs are not included in the list of forbidden headers, so this functionality has nothing to do with it, but merely shields the user from trying to send crap like `{ get: [Function] }` as headers.

**Comment by jcrben** [comment]
Technically that link applies to browser; nodejs prolly has a similar preference altho I'm not sure about the details.

Btw, I like the idea of preventing the user from shooting themselves in the foot, but I kinda prefer to throw with a helpful error message rather than messing around with what they've passed.

@nickuraltsev @rubennorte up for merging?

**Comment by zcei** [comment]
@jcrben I just stumbled through the code, and it looks like the `defaults.headers` can contain verb specific default headers.

E.g. for `POST` / `PUT` / `PATCH` (all three contain a request body) a default content type header is set. That's why they get removed on request 💡

**Comment by jcrben** [comment]
Err, good point - https://github.com/axios/axios/blob/db44a8f316da7e1f058eaed3556e9a391a2ffd3e/lib/defaults.js#L89 and https://github.com/axios/axios#global-axios-defaults

We really need integration tests.

**Comment by jasonsaayman** [comment]
Hi,

This fix does not seem suitable for the issue and does not have suitable tests.

Please open a new issue or pull request if this issue comes up again.

Thanks

**Pull request merged**
