### PR TITLE
Security fix for ReDoS

### PR DESCRIPTION
**Pull request by ready-research**
Fixes https://github.com/axios/axios/issues/3979

**Security fix for ReDoS vulnerability.**

https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String/Trim

Reported in https://www.huntr.dev/bounties/1e8f07fc-c384-4ff9-8498-0690de2e8c31/

**Before fix: Result**
```time_cost: 2968```
**After fix: Result**
```time_cost: 6```

### CODE REVIEW

**Comment by jasonsaayman** [comment]
@ready-research thanks for the fix :)

**Comment by ready-research** [comment]
@jasonsaayman Can you please confirm the same in https://www.huntr.dev/bounties/1e8f07fc-c384-4ff9-8498-0690de2e8c31/
By validating and confirming the fix.

**Comment by ready-research** [comment]
@zidingz Can you please provide access to @jasonsaayman and guide him to validate and confirm the fix.
Thank you

**Comment by ImRodry** [comment]
Could a release be published with this fix now that it has been merged?

**Comment by hreiner** [comment]
Same as ImRodry coud a release be published ?

**Comment by jasonsaayman** [comment]
Hi, I cannot release the project, I have asked everyone with access the moment that I released this. If there was a way for me to release it I would do so. I have also asked for access to be allowed to process releases.

**Comment by ImRodry** [comment]
Alright thank you! Hope that gets sorted quickly since I believe this is quite an important one

**Comment by kanatBektursyn** [comment]
I've got a question. Is it a normal way of dealing with security issue, when person opens up 10 discussions on several websites and shares it publicly?

**Comment by jasonsaayman** [comment]
Normally it is handled privately but in this case it seems to have not been. As for the earlier pull request, I have pretty much been trying to get through stuff on the repo but have also had some other stuff on my plate so was gone for a couple months. I will continue merging stuff and looking into issues more frequently now that I have more time.

**Comment by kanatBektursyn** [comment]
Thanks for the answer! Wish you the best

**Comment by GrvJava** [comment]
This is still getting flagged in snyk https://snyk.io/vuln/SNYK-JS-AXIOS-1579269

**Pull request merged**
