### PR TITLE
Correctly pass agents to follow-redirects

### PR DESCRIPTION
**Pull request by mhassan1**
This fixes https://github.com/axios/axios/issues/2546

### CODE REVIEW

**Comment by yasuf** [comment]
If I get a chance I'll merge a few PRs and add them to the 0.19.1 release, this one (although a really good fix) doesn't seem urgent to ship right away

If this is urgent for you, change the base to be the 0.19 PR branch and update the changelog and it'll go out on 0.19.1

**Comment by yasuf** [comment]
also you'll need to update the `dist/` folder

**Comment by mhassan1** [comment]
This PR should be part of 0.19.1 because #2426 will introduce a regression in 0.19.1 for anyone using http(s)Agent. I'll update the base of this PR and the changelog. Not sure if a dist change is required because this is only a change to `http.js`, but I'll check.

**Comment by mhassan1** [comment]
Closed in favor of https://github.com/yasuf/axios/pull/1

**Pull request closed without merging**
