### PR TITLE
Use different socket for Win32 test

### PR DESCRIPTION
**Pull request by timemachine3030**
Use different socket path for Win32

 - See: https://github.com/nodejs/node-v0.x-archive/blob/master/test/simple/test-pipe-stream.js#L73
 - Also: https://github.com/nodejs/node-v0.x-archive/blob/master/test/common.js#L39

### CODE REVIEW

**Comment by timemachine3030** [comment]
Not sure how this would specifically resolve the error in #3364 and I do not have a sauce key.

I tried testing Chrome 86, Win7, Node.js 10.0.0 multiple time with no error. Will try the Win10 failures when my VM finishes (tomorrow).

**Comment by chinesedfan** [comment]
Now the CI works well. If it is stable enough, we can ignore.

**Comment by timemachine3030** [comment]
This is still worth merging. Any developer on Windows, running the tests, will get an error.

**Comment by jasonsaayman** [comment]
I think this is a good idea to have it merged, there is a large user base on Windows and this could potentially keep people from contributing in the future and we don't want that.

**Pull request merged**
