### PR TITLE
Adding type AxiosInstance Constructor in AxiosStatic

### PR DESCRIPTION
**Pull request by md-adil**
adding type support for following use case

```js
import axios from "axios"; 
class Request extends axios.Axios { // Property 'Axios' does not exist on type 'AxiosStatic'

}

const request = new Request(axios.defaults);
request.get('<url>');

```

### CODE REVIEW

**Review by nurlansu — COMMENTED** [review]
Is it somehow related to https://github.com/axios/axios/issues/320?

**Comment by md-adil** [comment]
yes, but axios.Axios is not exposed in typescript.

https://github.com/axios/axios/issues/320#issuecomment-219140706 this will throw type error.

**Comment by Mini-ghost** [comment]
I think that's wrong. Because the object constructed through the Axios class is not the same as the function passed through `createInstance()`.

**Comment by md-adil** [comment]
Axios constructor is exposed here
https://github.com/axios/axios/blob/master/lib/axios.js#L32

but missing in type definition
https://github.com/axios/axios/blob/master/index.d.ts#L149

**Comment by Mini-ghost** [comment]
@md-adil It may be necessary to additionally define the type of the Axios class, like below ?

```ts
// index.d.ts

export class Axios {
  // Axios class properties and method
}


export interface AxiosStatic extends AxiosInstance {
  //
  Axios: Axios 
}
```

**Comment by md-adil** [comment]
@Mini-ghost 
interface for Axios is already declared here
https://github.com/axios/axios/blob/master/index.d.ts#L130
No need.

**Pull request closed without merging**
