### PR TITLE
Add CDNJS version badge in README.md

### PR DESCRIPTION
**Pull request by sufuf3**
This badge will show the version on CDNJS!

### CODE REVIEW

**Comment by todoconk** [comment]
👍

**Comment by jcrben** [comment]
@rubennorte @nickuraltsev small change which seems reasonable, let's keep these small things moving - either it's OK and accepted, or reject with a reason why. or ask for more information

leaving people in limbo discourages people from helping out

**Comment by sufuf3** [comment]
@Jamesking56 Thanks for the review.
The conflict was fixed. Would you please help me review this PR again?
Many thanks.

**Comment by nolleto** [comment]
The branch is out of date. Can you perform a rebase, please?

**Pull request merged**
