### PR TITLE
Fixing custom config options

### LINKED ISSUE #2203: Custom properties for config
So, if I understand it right, in 0.19.0 you've added `mergeConfig`
And this function filter config and remove custom properties from it.
It broke my solution for cancellation:

How it works:
```js
const requestManager = new RequestManager();
const instance = axios.create();
requestManager.patchAxiosInstance(instance);

const search = q =>
  instance.get('/search', {
    cancelable: true, // this is no longer possible in 0.19.0
    params: { q },
  });
```
Screenshot 2019-06-05 at 16 30 01

The solution:
```js
class RequestManager {
  constructor() {
    this.pendingRequests = new Map();
  }

  patchAxiosInstance(instance) {
    instance.interceptors.request.use(config => {
      if (!config.cancelable) return config; // this is no longer possible in 0.19.0

      const source = axios.CancelToken.source();
      const requestId = `${config.method}_${config.url}`;
      const cancelToken = source.token;
      this.addRequest(requestId, source.cancel);
      return { ...config, cancelToken, requestId };
    });

    instance.interceptors.response.use(response => {
      const { requestId } = response.config; // this is no longer possible in 0.19.0
      if (requestId) {
        this.removeRequest(requestId);
      }
      return response;
    });
  }

  addRequest(requestId, cancelFn) {
    this.cancelRequest(requestId);
    this.pendingRequests.set(requestId, cancelFn);
  }

  removeRequest(requestId) {
    this.pendingRequests.delete(requestId);
  }

  cancelRequest(requestId) {
    if (this.pendingRequests.has(requestId)) {
      const cancelFn = this.pendingRequests.get(requestId);
      cancelFn();
      this.removeRequest(requestId);
    }
  }
}
```

So, is it possible to relax filter in `mergeConfig` for custom properties? Because sometimes it is needed and very helpful in interceptors or somewhere else.

### PR DESCRIPTION
**Pull request by rafaelrenanpacheco**
This PR is a conflict fix of #2006 with some code style fix as well. The main work was done by @oleduc.

- fixes #2203

### CODE REVIEW

**Comment by rafaelrenanpacheco** [comment]
@jasonsaayman, here it is :+1:

**Comment by vvo** [comment]
I hate to do so, but seeing you did the last release @emilyemorehouse could you give us your advice on this PR? The caching module axio README provides is not working as of axios 0.19. Thanks!

**Comment by mohamedgomran** [comment]
When this can be merged? a lot of plugins has stopped working and waiting for this.

**Comment by akirilyuk** [comment]
When this will be merged? We would need to implement own solutions otherwise instead using plugins...

**Comment by codeclown** [comment]
@emilyemorehouse @nickuraltsev FWIW, as author of https://github.com/axios/axios/pull/1395 I'd approve this PR and merge it.

As messy as it is to allow including any properties carried around in the axios config, it was the past behaviour and should definitely be restored. I was not aware of such functionality being relied upon by third-party plugins when making the original PR.

**Comment by jondavidjohn** [comment]
Even if the breaking change stands, is there a strategy for plugins having custom config options to migrate to?

**Comment by eaviles** [comment]
Looking forward to see this resolved. It would fix: https://github.com/softonic/axios-retry/pull/82

**Comment by sustained** [comment]
Is this going to be merged?

**Comment by ruscon** [comment]
@rafaelrenanpacheco, can you approve this pull request ?

**Comment by KayHS** [comment]
Is there any ETA on this?

**Comment by simllll** [comment]
Anything we can do to get this into the master?

**Comment by jphilipstevens** [comment]
Hey,

I am a new maintainer for this project. I updated @emilyemorehouse about it. I see one conflict. I am happy to merge unless someone has a clear objection.

There is a conflict right now that needs to be addressed

**Comment by rafaelrenanpacheco** [comment]
@jphilipstevens all done!

**Comment by felipewmartins** [comment]
Can I merge this pull request?

**Comment by felipewmartins** [comment]
@jphilipstevens

**Comment by ruscon** [comment]
@rafaelrenanpacheco @felipewmartins as I see, the project does not use the merge strategy.

**Comment by rafaelrenanpacheco** [comment]
> @rafaelrenanpacheco @felipewmartins as I see, the project does not use the merge strategy.

what

**Comment by ruscon** [comment]
@rafaelrenanpacheco rebase if you can :)

**Comment by rafaelrenanpacheco** [comment]
> @rafaelrenanpacheco rebase if you can :)

I'll be able to rebase later today, stay tuned.

**Comment by rafaelrenanpacheco** [comment]
@jphilipstevens @ruscon @felipewmartins the branch is rebased and ready to go :rocket:

**Comment by felipewmartins** [comment]
Merged! Thanks @rafaelrenanpacheco

**Comment by jphilipstevens** [comment]
Thanks @rafaelrenanpacheco 

Does the version get built automatically? I can look tonight

**Comment by jphilipstevens** [comment]
The release cannot go out. There was a breaking change added by https://github.com/axios/axios/pull/2290 which causes the tests to fail.

Going through the commits since 0.19.0 I see that the tests worked fine up to commit b9931e0a95f7942f728c0de4ea7cbdef86bc360b and then broke with commit 89bd3abe9a98daa075be14587a616f8391040eb2

**Comment by simllll** [comment]
Did you find anything @jphilipstevens ? Can I help somehow?

**Comment by jphilipstevens** [comment]
Hey @simllll 
I tried to look into it one night. The errors that failed were the cancel token specs: https://github.com/axios/axios/blob/master/test/specs/cancel.spec.js

I checked out the master branch to validate and the commit I posted was the root cause. I was not able to fix. Any help would be appreciated. I can be on Gitter for anyone who wants to help.

**Comment by jphilipstevens** [comment]
Odd thing is the tests pass if you run them on their own with `fdescribe`

If you run the whole suite the cancel tests fail:
I see that an error is thrown
	Failed: Unhandled rejection.
	    at webpack:///test/specs/cancel.spec.js:75:0 <- test/specs/cancel.spec.js:121:17
	Failed: Unhandled rejection.
	    at webpack:///test/specs/cancel.spec.js:75:0 <- test/specs/cancel.spec.js:121:17

**Comment by manniL** [comment]
@jphilipstevens 	Anything we could do here to help out? :relaxed:

**Comment by jphilipstevens** [comment]
Let me try tonight or tomorrow morning. I need to checkout and build. I don't think it's done in the CI system like other projects I've used.

**Comment by felipewmartins** [comment]
Hi @jphilipstevens I fix the CI build. I think we are ready to generate a version 0.19.1

**Comment by jphilipstevens** [comment]
I tried last night but I don't think I have access to use bundlesize. I requested access for completing the release. Bundlesize is needed for prepublish. I'm figuring this out as I go. If anyone has a reason why bubdlesize fails with a 404 let me know.

I'm also on this projects Gitter (linked in the readme)

**Comment by simllll** [comment]
Thanks @jphilipstevens , i was just looking into the issue before I rechecked this thread. I was wondering why the tests did succeed on my platform, thanks for fixing it.

regarding bundlesize package, check if you can download bundlesize@0.18.0. I can download the 0.17 version, but installation fails. Maybe this is also the issue on your side? Orthe other way arround ;) ..try to fix the bundlesize version to 0.17 for ci build?

Regards
Simon

**Comment by OlegIvaniv** [comment]
Hey everyone,
really appreciate the great work that has been done on this. Is there an ETA for 0.19.1? 🙂

Cheers

**Comment by jphilipstevens** [comment]
Let me check tonight

**Comment by lhermann** [comment]
Any updates on this?

**Comment by simllll** [comment]
Thanks so far for axios, I'm doubtful right now if this library is really alive. For me I was looking for alternatives and I'm probably switching to https://github.com/sindresorhus/ky

Similar interface, covered by a nuxt module (https://http.nuxtjs.org/) and http2 support!

**Comment by jphilipstevens** [comment]
Unfortunately it's hard to get time in this project. My work has blocked GH access and I'm in the middle of transitioning to a new role. I am not sure who else has the ability to push this update. There are some manual steps here that are annoying and I am not sure that I could publish without that bundlesize token.

**Comment by levrik** [comment]
@jphilipstevens Sorry for the off-topic question... but how in the world are you able to work without GH access?

**Comment by rhyek** [comment]
This is ridiculous. Just wasted a whole day with this. Push the fix already.

**Comment by simllll** [comment]
For everyone: I just published versoin 0.19.1 on @hokify namespace if you want to use it, feel free.

just install @hokify/axios and change your includes from require('axios') to require('@hokify/axios').

npm https://www.npmjs.com/package/@hokify/axios

For axios maintainers:
There was actually no issue to publish it, I just did:
1.) https://github.com/axios/axios/pull/2410 applied most changes of this PR. not necessary, but I saw that there was a very old webpack version in it, and I didn't like that ;) THerefore I upgraded webpack too.

2.) npm run build

3.) npm run test (not even necesarry as the travis does this already)

4.) npm run publish

done :)

**Comment by EdwardDrapkin** [comment]
@simllll you can use yarn [custom resolutions](https://yarnpkg.com/en/docs/package-json#toc-resolutions) and specify something like `{ "resolutions": { "axios": "@hokify/axios" } }` in your package.json, and if you do that, you won't have to update your code while you wait for a fork to land upstream.  Hope this helps somebody!

**Comment by Boycce** [comment]
@simllll Cheers mate, I currently can't afford to wait

**Comment by filippoitaliano** [comment]
Hi! I rolled here from the discharge sequence of liability started on May 31st [here](https://github.com/axios/axios/issues/2190#issue-450563928). It's funny only because I managed to crack a cool workaround in my code...

**Comment by jphilipstevens** [comment]
Hey Everyone. 
I started a new job at a startup and have been working longer than expected. It's been hard to carve out time to work on Axios. I am not sure who else here has the needed access to help out. I think I will be occupied for about another month in order to help build out and onboard a new team in my job. 
I apologize for not being able to help more. After the last place cut off GH access that slowed down my ability to check-in and contribute to open source.

I know people are frustrated and long term I would love to redo Axios with things like Babel, CI/CD with enforcing test coverage standards, automated linting rules, etc. I guess depending on peoples interest and contribution we could try to get a plan in order but I see it taking time.

**Comment by evdama** [comment]
why not make more people maintainers so availablity of the individual is no blocker?

**Comment by jphilipstevens** [comment]
@evdama I was set up as a maintainer and I am not an owner or someone who has access to the settings in order to invite others.
I emailed the owner @emilyemorehouse and asked to be added before my old company blocked access to all of GH.

I would not mind being an owner. I really have little desire to be a gatekeeper here. If I could fix it trust me I would with the limited time I have.

**Comment by eaviles** [comment]
@jphilipstevens Happy to help here too. We are heavy users of Axios in our org.

**Comment by jphilipstevens** [comment]
@eaviles @thoean I've asked the owner for more privileges to be able to add contributors.

Since I am starting on a new role and building an engineering team I will have limited free time for Axios. If I can add others that would be great.

From my perspective I would argue for a short term vision of:
- stabilize the current 0.19.x build
- improve ci/cd for faster and consistent releases
- roadmap what a 1.0 would look like... There is a project here but I don't know it's state.

When I get a reply I will let others know.

**Comment by jasonsaayman** [comment]
I have triage access and have worked on trying to clear issues, however, without the access to merge pull requests it is very demotivating as one cannot actually make much of a difference or get to the actual issues at hand. @jphilipstevens I would also like to help with the repo as I use it in a number of projects and I would actually want to contribute to making the repo better.

**Comment by crobinson42** [comment]
@jphilipstevens there are several reddit threads and posts all over twitter criticizing the management of axios - the main thing I see being the criticizing point is the lack of spreading permissions to let the community HELP maintain the package - you said it yourself, you're too busy. This package has React.js weekly download numbers on NPM, LET THE COMMUNITY HELP MAINTAIN THE PACKAGE already!

**Comment by jphilipstevens** [comment]
@crobinson42 I get the frustration. I am a user of Axios as well. But to reiterate what I mentioned in a previous message. I do not have the ability to add new users. I have asked for the permissions and again as soon I hear back I can update people.

I also notice there is not commonplace to communicate with the community. Gitter was dead when I got on there. Is it Gitter? Reddit? I don't know. It would be great to have a place to reach out to everyone.

**Comment by kivervinicius** [comment]
:(

**Comment by richardkeller411** [comment]
Should just fork it and create an axios-2 with better permission and move community support to that?

**Comment by rhyek** [comment]
If it's possible to rally community support for said fork I think it's the best bet at this point. This repo is all but abandoned.

A discussion targeting that specifically would probably be a good idea, but it seems to me one of the focuses of said fork should include reworking the CI/CD strategy as that seems to be a huge blocker for publishing a new release in this repo, currently.

**Comment by yasuf** [comment]
I've talked to @emilyemorehouse  and prepared a PR for the 0.19.1 release, we just need a fix for https://github.com/axios/axios/issues before releasing the new version

**Comment by ruscon** [comment]
@yasuf Fixes for all 592 Issues?

**Comment by EdwardDrapkin** [comment]
I'd be willing to donate a significant amount of time to forking axios and porting it to typescript and calling it something different.  As long as we maintain compatibility with the existing axios ecosystem, that is.  And yeah, that would include closing out a bunch of issues and whatnot.

**Comment by crobinson42** [comment]
Edward, don’t need to ask just do it! Then post on twitter and dev blogs, you’ll be sure to get a huge following, is be willing to help you as well.

**Comment by kivervinicius** [comment]
@EdwardDrapkin  ky is this or no? https://github.com/sindresorhus/ky

**Comment by sambrezo** [comment]
I have been following this issue for a while and I would like to thank you all wholeheartedly for getting this fixed!

**Comment by EdwardDrapkin** [comment]
> @EdwardDrapkin ky is this or no? [sindresorhus/ky](https://github.com/sindresorhus/ky)

No.  `fetch()` still carries a performance penalty with large JSON payloads because it processes JSON differently than XHR does.  It also doesn't appear to be compatible with the existing axios ecosystem, which should be the highest priority of any fork.

**Comment by GeorgeZhangZHY** [comment]
when can this merge be released?

**Comment by GeorgeZhangZHY** [comment]
Even if a patch release (v0.19.1) would be appreciated. There are projects in need of this feature, and it's a little bit risky to revert axios back to 0.18.x.

**Comment by usb248** [comment]
so, seriously, i switch to https://www.npmjs.com/package/got package. This project seems to be dead. axios-retry package is broken owing to 0.19 release... https://github.com/softonic/axios-retry/issues/59.
👎

**Comment by adamreisnz** [comment]
Still no update? A lot of Axios plugins seem to be broken, what's the delay?

**Comment by OFreshman** [comment]
Can custom properties only be configured in the request interceptor?I can't get it in the instance or request。
Where did I use it wrong？

```
const service = axios.create({
  baseURL: `${baseUrl}`,
  headers: { 'Content-Type':'application/json' },
  // mysProp: 'sssss',  //can't get like this ?
})
```
OR
```
getData(obj = {}){
    return request.get(`/data/`,{
      params: obj,
      //myProp: 'sssss' // //can't get like this ?
    })
  },
```
it's succesful when i do as follow
```
service.interceptors.request.use(config => {
    // console.log('success request: ', config)
    config.myProp= 'requestHandler';
    return config;
  },
  error => {
    return Promise.reject(error);
  });
```

Does anyone know why? thanks

**Pull request merged**
