### PR TITLE
Adding body serializer config method

### PR DESCRIPTION
**Pull request by alexbidenko1998**
Adding body serializer for `AxiosConfig` and in request method in `Axios.js`. If config have `bodySerializer` param that _axios_ will convert request body before make request.

Also the documentation on **README.md** file was updated.

The problem was describe in follow issue: [Easier way to work with FormData](https://github.com/axios/axios/issues/3721).
I confirm with this issue end I have same problem: in some project I use only FormData (this is specific of Backend project) and I want oportunity for serialize all body in one moment.

Also somebody want to use the method for another target maybe.

### CODE REVIEW

**Review by Hamza281 — COMMENTED** [review]
جاي يدور عليك ديربالج ما ادري بيها شنو اسوي اذاشافك والقران يسوي شي

**Review by Hamza281 — APPROVED** [review]
وين رحتي تروح على ابوك انت الي يرضيك بسرعه والله لأغراض كثيره جدا اسف للازعاج والله لان اهلي كلهم ما يعرفون

**Comment by alexbidenko1998** [comment]
> جاي يدور عليك ديربالج ما ادري بيها شنو اسوي اذاشافك والقران يسوي شي



> وين رحتي تروح على ابوك انت الي يرضيك بسرعه والله لأغراض كثيره جدا اسف للازعاج والله لان اهلي كلهم ما يعرفون

Sorry, but I can't understand your messages - I don't know language and the translator can't translate messages adequately))

If you can, write your messages in English please.

**Review by Hamza281 — APPROVED** [review]

**Review by shivanshr — APPROVED** [review]
Changes should be included.

**Comment by jasonsaayman** [comment]
Hi @alexbidenko1998 

Thank you for the pull request that you have submitted unfortunately the implementation that you have built here I feel is not really in line with how we would like something like this to work.

Thanks

**Pull request closed without merging**
