### PR TITLE
Remove the skipping of "should support sockets" test

### PR DESCRIPTION
**Pull request by timemachine3030**
This PR re-enables the 'should support sockets' test. After review, the test is effective and passes an `npm test` run.

If a reason exists that this test is not effective or otherwise *should not* be included in the test run please explain in a comment so I can take additional steps to correct the test or remove it.

Thanks!

This pull request is the result of an in-depth code review I did on this package. You can read the complete review on my blog, http://ctrl-c.club/~timemachine/2020/10/24/code-review-axios/

### CODE REVIEW

**Comment by jasonsaayman** [comment]
@timemachine3030 thanks for the pull request, don't know why that test was skipped. By the way, your code review on `axios` is awesome, a great read!

**Review by chinesedfan — APPROVED** [review]
It was skipped by #1655 and I don't know why, either. No reason to refuse adding it back.

@timemachine3030 Really shocked by the detailed and professional code review, which also includes npm audit and test coverage. Some problems are known to us but we are not the original developers and it's hard to change them without a breaking refactor. If you are interested to join us and have enough time, I'd like to invite you as a collaborator.

**Review by jasonsaayman — APPROVED** [review]
LGTM

**Comment by chinesedfan** [comment]
Bad news. CI failed in Node.js 10/14. Maybe that's the reason why it was skipped. And it's annoying that the master branch runs additional tests.

**Comment by timemachine3030** [comment]
Thanks for the kind words all.

Looking at the CI builds I'm guessing that there is some tear down/cleanup missing from the `socket` test that is causing havoc. They don't fail in the same place nor is the failure consistent between versions (I don't think that it is a version number thing, I think that it is a timing issue). I'll try to reproduce here.

**Comment by timemachine3030** [comment]
I was able to reproduce a failure on Windows 7: node -v: 10.0.0

```
  1) supports http with nodejs
       should support sockets:
     Uncaught Error: listen EACCES ./test.sock
      at Server.setupListenHandle [as _listen2] (net.js:1313:19)
      at listenInCluster (net.js:1378:12)
      at Server.listen (net.js:1477:5)
      at Context.<anonymous> (test\unit\adapters\http.js:376:8)
      at process.topLevelDomainCallback (domain.js:121:23)
```

**Comment by timemachine3030** [comment]
@chinesedfan To answer your question on collaboration: Yes. I'm game for helping out. As a mention in the review, my company uses the package. They are willing to donate some of my development time to open source software.

**Comment by chinesedfan** [comment]
@timemachine3030 Good. Please send me your email address (mine is in the Github profile). Then we can invite you to our slack channel.

**Pull request merged**
