### PR TITLE
Fix Non-standard environment `pathname` is undefined #2799

### PR DESCRIPTION
**Pull request by icksky**
Fix Non-standard environment `pathname` is undefined #2799

### CODE REVIEW

**Comment by icksky** [comment]
This fix can't solve all problem in `Wechat Game Browser`. So, I'll close it.

**The best solution is to put `Wechat Game Browser` regarded as a non-standard browser.**

**But we can't set the result of `isStandardBrowserEnv`. Maybe can export some methods to do this.**

**Comment by raegen** [comment]
So, I'm not really sure how to put this, but, this error that you handled so aptly and after such an effortful examination and research, ultimately coming to the conclusion that "this fix can't solve all problem in Wechat Game Browser" so you'll close it. And you quite responsibly followed up by closing it immediately. So, here is the deal, my _Weekly Downloads: 34,823,424_ guy, it's your lucky day. Guess what my guy? You have become a grandpa. Your can't fix problem in Wechat Game Browser has multiplied. It's not affecting Wechat Game Browser only any longer. Congratulations! It happens in platform-dependant Chrome (which means potentially any or all of the other webkit browsers as well).
Even more importantly, congratulations to the other 34,823,424 million potential winners like me. 
Yeah

**Comment by icksky** [comment]
Sorry 34,823,424 guys (maybe 35,948,825 guys for now)......but _platform-dependant Chrome_ will lead the other problems. I think this problem should be solved from the root cause (to control the return result of `isStandardBrowserEnv`).

**Comment by raegen** [comment]
> I think this problem should be solved from the root cause (to control the return result of isStandardBrowserEnv)
That’s quite a curious way to say “this is irrelevant for the discussion, but I’d prefer fixing it in `./../utils` in the isStandardBrowserEnv function". It's really not my place, so I apologise in advance, but let me get this straight:
- you want to delegate assertions for every single, potentially inconsistent between browsers, implementation detail needed by basically any leaf utility/helper function, no matter how deep or specific it is, to one gatekeeper function called `isStandardBrowserEnv` (Windows webkit not adhering to these expectations kind of voids this definition _standard_), ultimately resulting in no isURLSameOrigin function - essentially an origin URL comparator - preventing the same origin check based on existence of a property on DOM HTMLAnchorElement?

**Comment by icksky** [comment]
you're right, we should target the problem, because `isStandardBrowserEnv` doesn't solve everything. But, I cannot reopen this PR because of the `master` branch is rename to `main`. I open a new PR #5242

**Pull request closed without merging**
