### PR TITLE
Fix: Don't add null values to query string. 

### PR DESCRIPTION
**Pull request by ChronosMasterOfAllTime**
This aims to resolve Feature Request #5107 and #5094

We added a "backwards compatibility" to allow serializing params with our own custom function instead of the current iterative toString approach.

### CODE REVIEW

**Comment by EfChouTR** [comment]
Yes please!

**Comment by ChronosMasterOfAllTime** [comment]
@jasonsaayman were there merge conflicts? Seems like some odd things from the merge. (Like the readme for example)

**Review by jasonsaayman — APPROVED** [review]
Looks good 🚀

**Comment by ChronosMasterOfAllTime** [comment]
Thank you!

**Comment by havardthom** [comment]
This PR contradicts the discusssion here https://github.com/axios/axios/issues/1139 and solution here https://github.com/axios/axios/pull/1987

I have a use case for `null` query param, as many people in  https://github.com/axios/axios/issues/1139 . Will this be added to Axios in the future?

**Comment by ChronosMasterOfAllTime** [comment]
> This PR contradicts the discusssion here https://github.com/axios/axios/issues/1139 and solution here https://github.com/axios/axios/pull/1987
> 
> I have a use case for `null` query param, as many people in  https://github.com/axios/axios/issues/1139 . Will this be added to Axios in the future?

Nulls were being included as empty string `some_param=`, not `some_param=null`. I would think you would want the latter. Also if your API is set to deserialze the QS it should automatically handle missing fields as null/nil/None/undefined.

**Comment by OzQu** [comment]
As far as I understood, there is multiple use cases to have query string with keys without values
```
  it('should support params', function () {
    expect(buildURL('/foo', {
      foo: 'bar',
      isUndefined: undefined,
      isNull: null
    })).toEqual('/foo?foo=bar&isNull');
  });
```
Could that be considered?

**Comment by EfChouTR** [comment]
@OzQu I get the ask, however if you look at the behavior, an unset query Param returns an empty string when parsed via `URLSearchParams`

image

If you want `null` as a value for `test`, it would have to be handled by your API. I would think omitting the value is the equivalent of `?someVal` when deserializing the request.

We can add it back in, but know it's up to the API to correctly handle this behavior when deserializing into your request object.

**Pull request merged**
