### PR TITLE
Fixed default transitional config for custom Axios instance;

### PR DESCRIPTION
**Pull request by DigitalBrainJS**
- Fixed default transitional config for custom Axios instances. Probably refers to #4049. To my surprise, the default configuration is not merged with the config for custom Axios instances, so it is not accessible for the code if the user creates its own Axios instance.
- Refactored `core/mergeConfig` helper

### CODE REVIEW

**Comment by jasonsaayman** [comment]
@DigitalBrainJS awesome lets try get this out with 0.22, can you rebase onto that branch?

**Comment by DigitalBrainJS** [comment]
@jasonsaayman Done. It looks like we will need to refactor the merge logic a bit more in the future since I see no reason why we need to support special `undefined` behavior only for the `validateStatus` option, since it can be set to null as TS typings defines, and the code doesn't actually rely on `undefined` only on `nullable`. Also, IMHO using `undefined` as the relevant value is a bad idea.

**Comment by jasonsaayman** [comment]
@DigitalBrainJS thats fine, can you please check conflicts? Please ping me when this is ready for me to finish up 0.22

**Comment by DigitalBrainJS** [comment]
@jasonsaayman Done.

**Pull request merged**
