### PR TITLE
feat: export getAdapter function

### LINKED ISSUE #5474: getAdapter method should became public to let adapters like axios-mock-adapter access http / xhr known adapters
### Describe the bug

libraries like axios-mock-adapter define an adapter but in same cases need to access to original adapter.

It was working correctly before as the adapter was always a function.
Now it can be an array of string

Only the method getAdapter() in adapters/adapter.js can allow access to original adapters (xhr and http)
But this method is not exported a all at top level.

Can you export it ? 

### To Reproduce

Try to use axios-mock-adapter plugin with onNoMatch option

### Code snippet

_No response_

### Expected behavior

_No response_

### Axios Version

1.2.1 and upper

### Adapter Version

_No response_

### Browser

_No response_

### Browser Version

_No response_

### Node.js Version

_No response_

### OS

_No response_

### Additional Library Versions

_No response_

### Additional context/Screenshots

_No response_

### PR DESCRIPTION
**Pull request by geekact**
`axios.defaults.adapter` has been converted to complex types since PR #5277 , therefore I decide to create this PR  for developers who want to enhance adapter.
```typescript
import axios, { getAdapter } from 'axios';

const defaultAdapters = axios.defaults.adapter; // string | function | (string | function)[] | undefined
axios.defaults.adapter = (config) => {
  // do something...
  const adapter = getAdapter(defaultAdapters); // fallback to default
  adapter(config);
  // do something...
}
```

Fixes #5474

### CODE REVIEW

**Comment by geekact** [comment]
I want to make sure this PR can pass CI, anybody help me to trigger workflows? Thanks a lot.

**Comment by geekact** [comment]
Hi, I'm always ready for your merge operation.

**Comment by ppmathis** [comment]
@DigitalBrainJS Would it be possible to have this PR merged / looked at? Various libraries like `axiosist` or `axios-extensions` are currently broken and users have to rely on pinning `axios` to `1.1.3` to still make use of them, as `axios.defaults.adapter` is no longer a function. Exposing said `getAdapter` function would make it possible to use the latest `axios` release again with these libraries. Thanks in advance for your consideration!

**Comment by zhenghangjie** [comment]
> axios.defaults.adapter is no longer a function. Exposing said getAdapter function would make it possible to use the latest axios release again with these libraries. 

So am I.
Thanks in advance for your consideration!

**Comment by marcin-wlodarczyk** [comment]
Can someone please review and merge this PR? getAdapter will be a handy addition.

**Comment by shallinta** [comment]
would it be possible to have this PR merged or release another package for a fetch/xhr adapter?

**Pull request merged**
