### PR TITLE
Fixing Z_BUF_ERROR when no content

### PR DESCRIPTION
**Pull request by lejahmie**
When response headers content-encoding is set but no content exist zlib fails with Z_BUF_ERROR.

Solution is to check if data exist, if it does not we should never try to decompress.
If no data exists, but content-encoding still says it is encoded we simply remove the header not confuse downstream operations.

### CODE REVIEW

**Comment by lejahmie** [comment]
Fixed issues with eslint tests

**Comment by jasonsaayman** [comment]
Thanks this looks good 😊

**Comment by lejahmie** [comment]
@jasonsaayman  you can probably close these when this is in;
https://github.com/axios/axios/issues/3989
https://github.com/axios/axios/issues/3648
https://github.com/axios/axios/issues/3055

**Comment by jasonsaayman** [comment]
Thanks will do

**Pull request merged**
