### PR TITLE
Fixing node types

### LINKED ISSUE #3219: Cannot find name 'ProgressEvent' when compiling TypeScript
#### Describe the bug
When trying to compile a Firebase function (Node.js / TypeScript) I get an error:
```js
node_modules/axios/index.d.ts:62:38 - error TS2304: Cannot find name 'ProgressEvent'.

62   onUploadProgress?: (progressEvent: ProgressEvent) => void;
                                        ~~~~~~~~~~~~~

node_modules/axios/index.d.ts:63:40 - error TS2304: Cannot find name 'ProgressEvent'.

63   onDownloadProgress?: (progressEvent: ProgressEvent) => void;
                                          ~~~~~~~~~~~~~
```

#### To Reproduce
Example of a `package.json` that fails to compile using `npm run build`.
```js
{
  "name": "functions",
  "scripts": {
    "lint": "eslint -c .eslintrc.js --ext .ts ./src",
    "lint-fix": "eslint -c .eslintrc.js --fix --ext .ts ./src",
    "build": "tsc",
    "serve": "npm run build && firebase serve --only functions",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "firebase": "firebase serve --only functions --port=8080",
    "deploy": "npm run build && npm run lint && firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "main": "lib/index.js",
  "dependencies": {
    "axios": "^0.20.0",
    "firebase-functions": "^3.10.0"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^3.9.1",
    "@typescript-eslint/parser": "^3.9.1",
    "eslint": "^7.7.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-import": "^2.22.0",
    "eslint-plugin-prettier": "^3.1.4",
    "prettier": "^2.0.5",
    "typescript": "^3.9.7"
  },
  "private": true,
  "engines": {
    "node": "10"
  }
}
```

#### Expected behavior
The Node.js code should compile.

#### Environment
 - Axios Version: 0.20.0
 - Node.js Version: 10.21.0
 - OS: Ubuntu 20.04

#### Additional context/Screenshots
None.

### PR DESCRIPTION
**Pull request by remcohaszing**
The `ProgressEvent` type comes from the `DOM` lib. This is typically unwanted when using axios in a NodeJS environment.

Fixes #3219

### CODE REVIEW

**Comment by chinesedfan** [comment]
@jasonsaayman Among related PRs, I prefer this one, which simply reverts the type to any. And users can assert the type by themselves.

- #3221, imports the DOM lib, which is not suitable for Node.js environment.
- #3228, provides ProgressEvent definition. But it lost the information that ProgressEvent extends from Event.

Similar debates are for `method/headers`(#2191/#2647). axios tries to provide more detailed enums, then it will prevent users to use other values. Unless all possible values are covered. But those values can be customized.

**Comment by Guillaume-Mayer** [comment]
I think @chinesedfan is right, simpler is better sometimes.
Out of curiosity, what is the matter with importing the DOM lib in a node environment? Since it's just typing.

**Comment by remcohaszing** [comment]
@Guillaume-Mayer 

> Out of curiosity, what is the matter with importing the DOM lib in a node environment? Since it's just typing.

Although these types currently don’t conflict, they might in the future. For a practical example, the types of `dom` and `webworker` do conflict, so they can’t be combined within the same project.

TypeScript should help by providing type information. If you’re working on a TypeScript project and somehow one types `document.createElement('')` in a file, one would expect TypeScript to fail over this.

Also a project that claims to work in a Node environment, shouldn’ require the user to specify they’re using a DOM environment, which is the current situation with Axios.

**Comment by jasonsaayman** [comment]
@chinesedfan I like this solution most too, do you think we should add this one into 0.20.1? I am happy to merge it and close the other PR's

**Comment by chinesedfan** [comment]
@jasonsaayman Sure. Friendly remind that breaking changes should be released in 0.21, instead of 0.20.1. To make things simple, we can release this PR in 0.21 together, though it looks like not breaking.

**Comment by remcohaszing** [comment]
This is non breaking.

**Review by jasonsaayman — COMMENTED** [review]
👍

**Comment by dfee** [comment]
While we wait for this fix to get published, create a `typings.d.ts` with the following:

```
/**
 * Fix for axios while we wait for ^0.2.1 to be published
 * merge: https://github.com/axios/axios/commit/b7e954eba3911874575ed241ec2ec38ff8af21bb
 * issue: https://github.com/axios/axios/issues/3219
 */
interface ProgressEvent {}
```

**Comment by karlhorky** [comment]
Rather than changing this to `any`, why not copy [the `ProgressEvent` types from `lib.dom.d.ts`](https://github.com/microsoft/TypeScript/blob/2644fb0b5cacdcdf905e7cfbae37f2781b6ab3a4/lib/lib.dom.d.ts#L11468-L11474)?

cc @jasonsaayman

**Pull request merged**
