### PR TITLE
fix axios.delete ignores config.data

### LINKED ISSUE #3220: Axios does not use data from config when making DELETE request
#### Describe the bug
Axios last version (0.20.0) does not use data from config when making DELETE request. In 0.19.2 it's working fine

#### To Reproduce

```js
axios.delete("...", { 
    data: { ids: [...] },
}).then(response => {
    ...
}).catch(error => {
    ...
});
```

#### Expected behavior
Axios send request data from config when making DELETE request

#### Environment
 - Axios Version 0.20.0
 - Browser Chrome 
 - Browser Version 84.0.4147.125
 - Node.js Version 12.18.3
 - OS: Linux Mint
 - Additional Library Versions React 16.13.1

#### Additional context/Screenshots
None

### PR DESCRIPTION
**Pull request by chinesedfan**
Fixes #3220. As explained in https://github.com/axios/axios/issues/3220#issuecomment-678643888.

### CODE REVIEW

**Comment by cuongdevjs** [comment]
How long this pr merged and release?

**Review by cuongdevjs — APPROVED** [review]

**Comment by ngajhede** [comment]
Yes please. This is currently breaking parts of our application.

A temporary solution is to use it like this
`axios.request({data, url, method: 'delete'});`

**Review by jasonsaayman — COMMENTED** [review]
Looks good 👍 I think this will help us with potentially breaking changes in the future.

**Review by jasonsaayman — COMMENTED** [review]
👍

**Comment by DanielIndie95** [comment]
@jasonsaayman why isnt that released yet? As I can see that the latest version is still 0.20.0

**Comment by MwumLi** [comment]
@jasonsaayman why isnt that released yet? npm version not match github tag

**Comment by lifesboy** [comment]
When will this version be released, please?

**Comment by pholleyad** [comment]
Adding another request for this to be released as well. Thanks @ngajhede for the workaround!

**Comment by jasonsaayman** [comment]
Hi All,

I am not able to do the release, only Emily can, I have spoken to her and I think we should see the release over the weekend.

Thanks

**Comment by rlightner** [comment]
@jasonsaayman any word from @emilyemorehouse?

**Comment by jasonsaayman** [comment]
I have asked again today to see when the release will happen, will update this thread as soon as I know whats going on.

**Comment by jasonsaayman** [comment]
Hi,

Version 0.21.0 has been released 🎉 please use that and let us know if that solves your issue.

Thanks

**Pull request merged**
