### PR TITLE
fix: Axios Response with wrong "unknown" data property type

### PR DESCRIPTION
**Pull request by ArthurPedroti**
In the Axios Error type, the generic type T is defined as "any", but the previous type is overriding this type and setting it to "unknown":

image

What was done:

I updated the unknown to any at the AxiosError because it's only used in response property and don't affect any other property.

### CODE REVIEW

**Comment by ArthurPedroti** [comment]
@jasonsaayman Please check now with the conflicts resolved

**Comment by ArthurPedroti** [comment]
@jasonsaayman Can you check and merge this little tweak?

**Comment by ArthurPedroti** [comment]
@jasonsaayman Hey Jason, sorry for the inconvenience, but can you merge de PR, please?

**Comment by arananegra** [comment]
Hi! I'm dealing with this same problem. Wherever I try to use 

`	.catch((reason: AxiosError) => {`

And then use a field that the backend sends like: `reason?.response?.data?.errorMsg` (knowing that the backend will return that) typescript screams: TS2339: Property 'errorMsg' does not exist on type 'unknown'.

Has anyone been able to resolve this? I use this pattern in a lot of places around my codebase and a refactor will be a huge effort

**Comment by jasonsaayman** [comment]
closing stale and failing ci, will address types in a larger re-factor

**Pull request closed without merging**
