### PR TITLE
Refactored project file structure to avoid circular imports;

### PR DESCRIPTION
**Pull request by DigitalBrainJS**
#4177

### CODE REVIEW

**Comment by ammichael** [comment]
Hey there. How can we bump this PR?

**Comment by DigitalBrainJS** [comment]
@jasonsaayman Would you like to review and consider merging this PR? Because of this, we get a lot of the same bug reports.

**Comment by jasonsaayman** [comment]
Done @DigitalBrainJS thank you for this

**Comment by maryjenel** [comment]
hiii @jasonsaayman @DigitalBrainJS thank you so much! Do we have a timeline on when this will be released?

**Comment by jasonsaayman** [comment]
I will create a branch to make a minor version to update this.

**Comment by jasonsaayman** [comment]
Released 0.26.1

**Pull request merged**
