### PR TITLE
Adding support for tracking redirects

### LINKED ISSUE #1731: no redirects history
Current Axios version can't track redirects, because of using `follow-redirects` library (see #834).
Since v1.5.0 `follow-redirects` library supports `trackRedirects` pre-request option that stores the redirected response details into the redirects array on the response object

#### Summary

Please add new option `trackRedirects` to request config.

#### Context

- axios version: *e.g.: v0.18.0*
- Environment: node v10.7.0

### PR DESCRIPTION
**Pull request by gcox**
Resolves #1731 

It is important for some systems to know when a redirect occurs, especially when a redirect is permanent (crawlers, aggregators, etc). Since [follow-redirects](https://github.com/follow-redirects/follow-redirects) supports tracking redirects now, it is useful to add the feature to `axios` as well. 

The changes are quite simple, a new option has been added called `trackRedirects`, with a falsy default. The http adapter was modified to pass the option to the transport's request function. When the transport response comes back, if `trackRedirects` is enabled, the transport response's `responseUrl` and `redirects` values are tacked onto the axios response.

### CODE REVIEW

**Comment by JCMais** [comment]
would love this being merged

**Comment by phgroe** [comment]
Another 👍 for merging this from me. Setting up `follow-redirects` manually is, for some reason, a huge PITA and using Axios instead with its nice Promise-API is much smoother.

I'm using this feature for integration tests to check if redirects work on a website, having to check all the intermediate hops. Hacked two lines into the Axios here in my project's _node_modules_ (one for setting `trackRedirects` and one for appending `redirects` to the response object) and it worked just fine.

When can we expect this to land in master? Any help needed?

**Comment by phgroe** [comment]
Just realized that the definition of `trackRedirects` is missing in the main `index.d.ts` typings file.

@gcox please add
```
trackRedirects: boolean;
```
to the interface `AxiosRequestConfig` there. Thanks 😄

**Comment by gcox** [comment]
@phgroe I'm sorry, I completely missed the notification from your comment back in March🤦‍♂ I've made the change and merged in the latest changes from master. Hopefully someone with permission will review/merge this soon🤞

**Comment by laurent35240** [comment]
HI,

Is there any plan to merge this pull request and add this feature in axios soon?

Thx,
Laurent

**Comment by gcox** [comment]
@laurent35240 I resolved the conflicts with master and requested a review. Hopefully it'll get addressed soon.

**Comment by humphreyn** [comment]
Hi, when can we expect this fix to be merged into master?

**Comment by jasonsaayman** [comment]
@humphreyn I marked this as v1 so it would probably only be merged after v0.20 releases.

**Comment by jasonsaayman** [comment]
@gcox can you please check build is failing?

**Comment by jasonsaayman** [comment]
@gcox thanks 👍

**Comment by markb-trustifi** [comment]
I tested it and it seams to be not working:
`axios.get('https://shorturl.at/vGT45', {maxRedirects:15}).then(...)`

The res.redirects is always empty.

**Comment by edbordin-linktree** [comment]
Did this feature never make it out of beta or has it been removed?

**Pull request merged**
