### PR TITLE
Remove unnecessary XSS check introduced by #2451

### LINKED ISSUE #2646: Requests to urls containing 'javascript' are failing
It seems that axios v0.19.1 introduced a new bug. 

The bug comes from https://github.com/axios/axios/pull/2464

All urls containing `javascript`keyword is throwing XSS error.  So, all following urls cannot be used in axios any more:

- https://www.javascript.com
- https://stackoverflow.com/questions/tagged/javascript
- https://www.google.com/search?q=javascript

Here is a link to regexp: https://regexr.com/4rsst

Expected behavior: axios should accept `javascript` in urls

### PR DESCRIPTION
**Pull request by chinesedfan**
Fixed #2646 and lots of similar issues.

I shared the same opnion with @snoopysecurity. See https://github.com/axios/axios/pull/2464#issuecomment-542430885. We did overreaction for it and did an overkill.

### CODE REVIEW

**Comment by edgarjrg** [comment]
@chinesedfan How can I have this fix ? I have a #2646 issue

**Comment by chinesedfan** [comment]
@edgarjrg I don't know. But I will try to ask members who have publish permissions to release soon.

@danielyeshua Can you elaborate your question?

**Comment by danielyeshua** [comment]
There is still no solution for those who use AXIOS in this way: <script src = "main.js"> </script>

There may be and I have not yet left.

**Comment by chinesedfan** [comment]
@danielyeshua Never mind. When the next version is released, those dist files will be updated corresponding.

**Comment by snguyens** [comment]
Getting this error with this new release:  Error: Unable to resolve module `./isValidXss` from `/Users/snguyen/Desktop/repos/howzbout-app/node_modules/axios/lib/helpers/isURLSameOrigin.js`:

**Comment by timaxxer** [comment]
I am wondering if there is anything else that will help covering the issue of XSS in `helpers/isURLSameOrigin.js`

In my organization, I run a scan on my app with Synopsys Coverity and this is higlighting a Critical XSS issue in `helpers/isURLSameOrigin.js`
https://github.com/axios/axios/blob/master/lib/helpers/isURLSameOrigin.js#L30

```
CVSS Severity: Critical
CWE 79: Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')
This CWE entry is at position 7 in the OWASP Top 10.
This CWE entry is at position 4 in the CWE/SANS Top 25.
```

Let me know if this can be addressed or not.

**Pull request merged**
