### PR TITLE
Fixed decompression for responses without `Content-Length` header

### LINKED ISSUE #5296: 1.2.0 transformResponse
### Describe the bug

When upgrading from `1.2.0-alpha.1` to just `1.2.0` the config `transformResponse` sends data as binary instead of string.

### To Reproduce

_No response_

### Code snippet

_No response_

### Expected behavior

_No response_

### Axios Version

_No response_

### Adapter Version

_No response_

### Browser

_No response_

### Browser Version

_No response_

### Node.js Version

_No response_

### OS

_No response_

### Additional Library Versions

_No response_

### Additional context/Screenshots

_No response_

### LINKED ISSUE #5298: Error response data nodejs
### Describe the bug

`
var axios = require('axios');
var data = JSON.stringify({
  "production_status": "",
  "package_status": [],
  "extra_status_reason": [],
  "page": 1,
  "limit": 1
});

var config = {
  method: 'post',
  url: 'https://example.com/',
  headers: { 
    'Authorization': 'Bearer token', 
  },
  data: {
    "production_status": "",
    "package_status": [],
    "extra_status_reason": [],
    "page": 1,
    "limit": 1
  }
};

axios(config)
.then(function (response) {
  console.log(response.data);
})
.catch(function (error) {
  console.log(error);
});
`

When i send API this response
image
I want respose must be json like that
image

### To Reproduce

_No response_

### Code snippet

_No response_

### Expected behavior

_No response_

### Axios Version

1.2.0

### Adapter Version

_No response_

### Browser

_No response_

### Browser Version

_No response_

### Node.js Version

14.20.1

### OS

_No response_

### Additional Library Versions

_No response_

### Additional context/Screenshots

_No response_

### LINKED ISSUE #5313: Axios response data looks wierd in my powershell
### Describe the bug

I try to fetching data using axios :

```js
const URL = "https://jsonplaceholder.typicode.com/users"

axios.get(URL)
.then((res) => console.log(res.data))
```

but when it's done and i try to access the result using pwsh or cmd : 

Screenshot 2022-11-26 211341

Data is displayed in wrong format but in my browser it is displayed in the correct format : _Object / JSON_

### To Reproduce

```js
const URL = "https://jsonplaceholder.typicode.com/users"

axios.get(URL)
.then((res) => console.log(res.data))
```

### Code snippet

_No response_

### Expected behavior

_No response_

### Axios Version

_No response_

### Adapter Version

_No response_

### Browser

_No response_

### Browser Version

_No response_

### Node.js Version

_No response_

### OS

_No response_

### Additional Library Versions

_No response_

### Additional context/Screenshots

_No response_

### LINKED ISSUE #5314: Getting 401 Unauthorized in v1.2.0 with same code that returned 200 with v1.1.3
### Describe the bug

A logon sequence works perfectly well with axios v1.1.3
Changing nothing more than axios from v1.1.3 to 1.2.0 now results in 401 Unauthorized

### To Reproduce

Unfortunately, I cannot reveal the entire log for security reasons
I have studied the detailed axios interceptor logs of a successful v1.1.3 vs failed v1.2.0 session
I have seen the following major difference

1.1.3:  response data is logged as plain text, Logging using axios interceptiors:
  data: '<!DOCTYPE HTML>\r\n' +
    '<html lang="en">\r\n' +
    '<head>\r\n' +

1.2.0: response data is not decoded when logged, Logging using axios interceptiors:
  data: '\x1F�\b\x00\x00\x00\x00\x00\x00\x03�=ks�Fr߯���\x18�ZJ�@\x12|��J\x1B���*��U��c;�\x010 g\x05`p\x00(�v\\�����_��\x19�\b�"���%�e�\x04���ӯ��\x01_\x7F��ǣ�\x1Fώɻ���\x07\x7F���q�{ģ�h_c�&�0���

### Code snippet

_No response_

### Expected behavior

I expect v1.2.0 to work same as v1.1.3 after an upgrade from 1.1.3 to 1.2.0

### Axios Version

1.2.0

### Adapter Version

http

### Browser

n/a, this is a logon sequence to connect to a device via http

### Browser Version

_No response_

### Node.js Version

18.12.1

### OS

Microsoft Windows 10 Home (10.0.19045)

### Additional Library Versions

```bash
"axios-cookiejar-support": "^4.0.3",
"axios": "=1.1.3", // 1.2.0 fails
"mqtt": "^4.3.7",
"qs": "^6.11.0",
"tough-cookie": "^4.1.2"
```

### Additional context/Screenshots

_No response_

### LINKED ISSUE #5315: Getting unreadable data in response from external API
### Describe the issue

I've deployed successfully my backend to a serverless cloud service, but, unlike the local version, in the hosted app I'm getting an unreadable response rather than JSON as you can see below.

`"�\b�T�r�8���r�i�.~����FH�!�\t�01C���\\��*Y�T��e�{�=��{��NgY?_�]��Aӝ�.yQw?k/?��۬=�|���<��#�dd3)��6���l2\nJ]X��������e��^�?\r|�H`

### Example Code

```js
app.get('/api/get-my-books', (req, res) => {

    const address = req.query.address;
    const chain = "polygon";

    const options = {
        method: 'GET',
        url: `https://api.nftport.xyz/v0/accounts/${address}`,
        params: {
          chain: chain,
          include: 'metadata',
          contract_address: process.env.REACT_APP_DROP_CONTRACT
        },
        headers: {
          'Content-Type': 'application/json',
          Authorization: process.env.REACT_APP_NFT_PORT
        }
      };
      
      axios.request(options)
      .then((response) => {
        res.json(response.data);
      })
      .catch((error) => {
        console.error(error);
      });
});
```

### Expected behavior

A readable JSON response is expected.

### Axios Version

1.2.0

### Adapter Version

_No response_

### Browser

Chrome

### Browser Version

_No response_

### Node.js Version

14.19.1

### OS

_No response_

### Additional Library Versions

```bash
"cors": "^2.8.5",
"dotenv": "^16.0.3",
"express": "^4.18.2"
```

### Additional context/Screenshots

_No response_

### PR DESCRIPTION
**Pull request by DigitalBrainJS**
- doesn't rely on `content-length` header, avoiding `Z_BUF_ERROR`;
- added `compress` encoding to `Accept-Encoding` request header;
- disabled decompression attempt for `HEAD` request;
- add Brotli encoding to the `Accept-Encoding` header only if it is supported

Closes #5298 
Closes #5296 
Closes #5313;
Closes #5314;
Closes #5315;

Suggested release: `1.2.1`

### CODE REVIEW

**Review by CarstenLeue — COMMENTED** [review]
The line
```ts
const responseLength = +res.headers['content-length'];
```

will still result in `NaN` for the `responseLength` which is then used for the download progress. 
Does it make sense to show progress if no length is available?

**Comment by DigitalBrainJS** [comment]
> will still result in NaN
That is previously worked code, it handles NaN.
> Does it make sense to show progress if no length is available?
Of course, the length may not be present when the ProgressEvent emits.

**Comment by karlhorky** [comment]
Does this also close #5311 ?

**Comment by DigitalBrainJS** [comment]
@karlhorky Unlikely. This PR fixes the regression bug with response decompression in v1.2.0, but it looks like that issue is related to request failure.
In any case, to be sure, it should be tested on v1.2.0-alpha.1 which does not have this bug.

**Comment by jsiegenthaler** [comment]
Hi @DigitalBrainJS I can confirm that 1.2.0-alpha.1 fixes the observations I made of uncompressed date in #5314
My core issue in #5314 remains unsolved at the moment, but at least the decompression is now working, and I can cross that off my list of things to check.

**Comment by karlhorky** [comment]
Yeah `axios@1.2.0-alpha.1` also fixed my problem from #5311:

- https://github.com/axios/axios/issues/5311#issuecomment-1328279883

**Comment by depyronick** [comment]
this is a shame

**Comment by DigitalBrainJS** [comment]
@jasonsaayman Can we have a patch release with this?

**Comment by jasonsaayman** [comment]
Yeah sure, I will get to this one asap

**Comment by davidfilat** [comment]
> Yeah sure, I will get to this one asap

Any time...

**Comment by deepak786** [comment]
When we can expect the new release 1.2.1?

**Comment by jasonsaayman** [comment]
I am working on that, might be a 1.3.0 in all honesty

**Comment by DigitalBrainJS** [comment]
@jasonsaayman IMHO hotfixes are best released separately from minor changes, as such releases have a higher priority. This is more reliable because we can fix one thing but break another, probably not covered by tests, and the whole release becomes useless. Therefore, if we have a broken minor release (with a critical regression bug), we should release a patch to fix it, and only then publish a minor release with other changes.

**Comment by mlippert** [comment]
So `axios@1.2.0-alpha.1` fixes the issue I just ran into after upgrading to `1.2.0`.

I did want to point out that semantic version number wise, this prerelease probably should have been `1.2.1-alpha.1`.

because when comparing versions: `1.2.0-alpha.1` < `1.2.0` < `1.2.1-alpha.1` < `1.2.1`

Not really a big deal right now testing this, but thought I'd mention. You can see if you do the following:
```
$ npm i axios@1.2.0-alpha.1
$ npm outdated
Package        Current  Wanted  Latest  Location            Depended by
axios    1.2.0-alpha.1   1.2.0   1.2.0  node_modules/axios  riffcollector
```

**Comment by DigitalBrainJS** [comment]
> So axios@1.2.0-alpha.1 fixes the issue I just ran into after upgrading to 1.2.0.

@mlippert No, it doesn't fix the issue. It's just the last working version before `v1.2.0` without the regression bug that was released 23 days ago. This fix has not yet been released.

**Comment by mlippert** [comment]
> > So axios@1.2.0-alpha.1 fixes the issue I just ran into after upgrading to 1.2.0.
> 
> @mlippert No, it doesn't fix the issue. It's just the last working version before `v1.2.0` without the regression bug. Alpha was released 23 days ago. This fix has not yet been released.

Sorry, didn't realize that's what that release was. I just tried it and the failure I was seeing didn't occur, but that was the regression. I thought that release was a proposed fix. So that was the same as my re-installing `1.1.3` and gave you no useful information. I apologize, I got here via  #5328.

**Comment by MidnightTinge** [comment]
Sorry for the noise but any updates on a patch release? This is a non-obvious, app-breaking bug that wastes a lot of time tracking down. The only fix is to either disable decompression or downgrade, so it's a bit awkward that it's taking this long to get a patch out. I know people are busy, but I don't really think this is a back-burner kind of bug 😅

**Comment by DigitalBrainJS** [comment]
@MidnightTinge Unfortunately, this doesn't depend on me since I'm not a repo/npm collaborator. The only hope is that @jasonsaayman can find some time to make a release. For now, you can use the previous alpha version, as it is almost the same as this one, but working :) 
Maybe we should make a CI release script to reduce the release effort and thus enable more frequent releases, but this task is also very labor-intensive.

**Comment by philBrown** [comment]
> might be a 1.3.0 in all honesty

This is a terrible approach to semantic versioning that seems prevalent since v1.0.0. You seem to be continuously leaving a slew of broken minor releases in your wake. Anyone using `~version` is left with absolutely no recourse.

Please do your users a favour and do patch releases.

**Comment by jasonsaayman** [comment]
I will release it tonight, I will also release it as 1.2.1. I will also try to get to these quicker in the future. @philBrown thanks for that observation, there have been multiple issues fixed in those releases. Also whenever there is a type change I prefer to bump the minor otherwise there will be a lynch mob of people coming at me with threats or hate speech. It has been a rocky start to v1.x but I believe we are moving things in the right direction. I will try please as many people with versioning as I can but I can assure someone will hate what I do either way.

**Comment by jasonsaayman** [comment]
> Maybe we should make a CI release script to reduce the release effort and thus enable more frequent releases, but this task is also very labour-intensive.

@DigitalBrainJS I have been thinking about trying to get this done, I will probably look into it over the next while. I can also gran you a token to help with more, lets chat.

**Comment by jasonsaayman** [comment]
@DigitalBrainJS I have elevated your access on this repo 😃

**Pull request merged**
