### PR TITLE
chore: add `jsdelivr` and `unpkg` support

### PR DESCRIPTION
**Pull request by JounQin**
As title

### CODE REVIEW

**Comment by yasuf** [comment]
I see we have axios already in https://cdnjs.com/libraries/axios ? Also we have `main` in the `package.json` already (https://github.com/jsdelivr/jsdelivr#configuring-a-default-file-in-packagejson)

**Comment by JounQin** [comment]
The `main` field file is node module, not point to umd or CDN file.

**Comment by yasuf** [comment]
@JounQin as per https://github.com/axios/axios/pull/1110, axios is already on jsdelivr and unpkg somehow, why do we need to add this as well?

**Comment by yasuf** [comment]
I see https://github.com/jsdelivr/jsdelivr#publishing-packages, so all our versions should be available in jsdelivr as long as we push them to npm

**Comment by yasuf** [comment]
closing unless I'm missing something, feel free to repoen

**Comment by MartinKolarik** [comment]
@yasuf those fields are not required but make it easier to discover and use the correct file. jsDelivr supports `main` as well but that points to `index.js` instead of `dist/axios.min.js` so this PR makes sense.

**Comment by JounQin** [comment]
。。。

**Comment by JounQin** [comment]
@yasuf you asked the same question before, and I've answered it like @MartinKolarik 's comment, and then you approved this  PR. But now you asked the same question...

**Comment by yasuf** [comment]
sorry @JounQin, I hadn't seen the jsdelivr documentation before, as I see right now, both jsdelivr and unpkg links work, and yes, the current `main` has a different purpose.

The links for the CDNs work fine right now, the part I'm missing is why we need these explicitly instead of having those services take the files from npm? If so, should it point to the regular `dist/axios.js` or the minified version?

Current links:
https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js
https://unpkg.com/axios/dist/axios.min.js

Even the non-minified versions are up

**Comment by JounQin** [comment]
Personally I prefer:

https://cdn.jsdelivr.net/npm/axios
https://unpkg.com/axios

So that I don't have to know the exact location of `dist` file, and it should benefit users who doesn't use npm/package manager.

**Comment by MartinKolarik** [comment]
@yasuf in case of jsDelivr, that field is used by jsDelivr website/API to indicate which file is the "right one", plus it allows using the shorter link. It should be the minified version (even if you set `axios.js`, jsDelivr will convert it to `axios.min.js`)

**Comment by yasuf** [comment]
@JounQin can you update it to be the minified file?

**Comment by JounQin** [comment]
@yasuf Done.

**Comment by JounQin** [comment]
@yasuf Can we get this PR merged?

**Pull request merged**
