### PR TITLE
Exposing the Axios constructor in index.d.ts

### LINKED ISSUE #3017: Align auto-import with README examples
**Is your feature request related to a problem? Please describe.**
When you copy'n'paste examples from the README into you code, you can't easily auto-import (e.g. in VS Code) the Axios lib.

**Describe the solution you'd like**
I'll rename the default export in the `index.d.ts` so it alignes with the official documentation.

Change this:
image

image

To this:
image

image

**Describe alternatives you've considered**
Change all the official examples to use `Axios` instead of `axios` ;)

**Additional context**
Nothing.

### PR DESCRIPTION
**Pull request by TimWolla**
This patch allows TypeScript users to extend the `Axios` class without
the type checker complaining.

see 7548f2f79d20031cd89ea7c2c83f6b3a9c2b1da4

----------

Fixes #3017

### CODE REVIEW

**Comment by TimWolla** [comment]
Could you please take a look? After I used the “Update branch” button on April, 8th Travis is green instead of a stuck yellow as well.

**Comment by donaldpipowitch** [comment]
@chinesedfan Is there something which still needs to be done for this MR?

**Comment by ArrayKnight** [comment]
Would it possible to get this merged soon, please?

**Comment by jasonsaayman** [comment]
Will look at this as soon as I can

**Comment by farah** [comment]
Just a friendly bump, would love to see this change merged soon.

**Comment by TimWolla** [comment]
@remcohaszing Can you return the favor and review this one, please? The reason behind this change is being able to `class Foo extends Axios` with `import { default as axios, Axios } from 'axios';`.

It should be non-breaking, but a second pair of eyes would be helpful.

**Comment by remcohaszing** [comment]
I looked into it. This allow to use the following statements that were previously not possible:

```ts
import axios from 'Axios';

const foo = new axios.Axios();  // Use Axios constructor
foo instanceof axios.Axios;  // Instanceof check for Axios instance
foo('/');  // This is unsupported, and now also an error in TypeScript
```

The `instanceof` check doesn’t work for instances created `axios.create()`, but the call expression does work in that case.

All of these cases are properly handled by the new type definitions, and it’s non-breaking. LGTM :smiley:

**Comment by TimWolla** [comment]
@jasonsaayman I'd appreciate if you could take a look at this one. I'm happy to answer all your questions about it, like we did in #2797 :+1:

**Comment by TimWolla** [comment]
@jasonsaayman Friendly ping. I just rebased this PR once again and it's already been reviewed by Remco.

**Comment by TimWolla** [comment]
@jasonsaayman Any chance? I just rebased the PR onto the latest `master` to allow for the GitHub Actions to run. You'll need to approve them once, though, because technically I'm a new contributor.

**Comment by jasonsaayman** [comment]
@TimWolla thanks for being so tenacious, I am merging this now 🥳

**Comment by TimWolla** [comment]
Thanks! 🚀

**Pull request merged**
