### PR TITLE
Adding CI on Github Actions.

### PR DESCRIPTION
**Pull request by koh110**
#### Instructions

Context: https://github.com/axios/axios/issues/3718#issuecomment-890455690

Adding CI on Github Actions.

PRs have also stopped CI around June. I think Travis CI needs to be migrated to another domain.
I don't know the CI migration plan for the axios project.
So, I added CI on Github Actions until CI worked again.

#### Additional context
https://github.com/axios/axios/issues/3930
https://github.com/axios/axios/pull/3916

### CODE REVIEW

**Comment by jasonsaayman** [comment]
Hi, Thanks I will do, I will be more active again in the weeks to come.

**Comment by koh110** [comment]
@jasonsaayman Thanks! I hope that the axios project will move forward.
Please let me know if you have any help.

**Comment by jasonsaayman** [comment]
@koh110 seems to have passed however I don't see how we are going to handle browser based testing?

**Comment by jasonsaayman** [comment]
> @koh110 seems to have passed however I don't see how we are going to handle browser based testing?

Don't worry, I have answered my own question

**Comment by jasonsaayman** [comment]
@koh110, thanks very much for making this work, super grateful for your contribution 🥇

**Comment by rigor789** [comment]
Hi @koh110 - I think there is a small mistake in the workflow, the matrix defines `node-version` and in `setup-node` it's reading `matrix.node` - and I think all 3 builds use the default node version as a result.

https://github.com/axios/axios/blob/f3ca6371caa738ba5308d413433d9f676f2e0138/.github/workflows/ci.yml#L15

https://github.com/axios/axios/blob/f3ca6371caa738ba5308d413433d9f676f2e0138/.github/workflows/ci.yml#L19-L22

**Comment by jasonsaayman** [comment]
@rigor789 could you put in a pull request to fix?

**Comment by rigor789** [comment]
@jasonsaayman sure, here it is https://github.com/axios/axios/pull/4069

**Comment by koh110** [comment]
@rigor789 @jasonsaayman Thank you for fixing my bug!  I didn't notice it.

**Pull request merged**
