### PR TITLE
Fixing memory leak in isURLSameOrigin

### PR DESCRIPTION
**Pull request by xinpingwang**
Fixing memory leak in isURLSameOrigin described in #2489

### CODE REVIEW

**Comment by HJM515** [comment]
I have a simple question about your changes. why you put XSS validate in 'isURLSameOrigin'? which is better？

I have a question about the method (isURLSameOrigin). Why 'isURLSameOrigin' just compare protocol and host, no port? 

Hope can get your comments. Thank you.

**Comment by xinpingwang** [comment]
1. In the origin implementation `originURL` is get by `resolveURL(window.location.href)`, means `originURL` will also be checked by XSS validation.  After change, `originURL` is get by `window.location`, to ensure it still be checked. XSS validate is put in `isURLSameOrigin`.

2. According to the definition of [Same Origin Policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy), both `protocol`, `port` and `host` should be checked, I'm sorry for not notice this issue, and I will push a commit to fix it.

Thanks.

**Comment by HJM515** [comment]
I get it. Thank you for your guidance.

**Comment by HJM515** [comment]
Another question, resolveURL just can be use in isURLSameOrigin,  if protocol and host is enough, why resolveURL return so many props? Just for meet the meaning？

**Comment by xinpingwang** [comment]
I have explore whole the project, resolveURL is just used by isURLSameOrigin, I think so many props returned is to meet the meaning, makes it working like an URL object.

**Comment by jasonsaayman** [comment]
Closing please check #2489

**Pull request closed without merging**
