### PR TITLE
Compatible with follow-redirect aborts the request

### LINKED ISSUE #2691: Let's establish a closer relation with follow-redirects
Hi axios maintainers,

I'm the maintainer of follow-redirects. According to npm numbers (https://www.npmjs.com/package/axios, https://www.npmjs.com/package/follow-redirects), more than half of follow-redirects usage goes via axios. That is also apparent from several [bug reports](https://github.com/follow-redirects/follow-redirects/issues?q=axios) I received (and which I'm very happy about).

So if there are issues such as https://github.com/axios/axios/pull/1993 or https://github.com/axios/axios/pull/2689, it's probably best to ping us about it at https://github.com/follow-redirects/follow-redirects/issues/new. I'm very happy to fix. Pinning to an old version of follow-redirects will just expose you to bugs.

Please let me know how I can help.

CC: @grumblerchester @emilyemorehouse @realityking @chinesedfan

### PR DESCRIPTION
**Pull request by chinesedfan**
Preparation for #1804. Closed #2691.

follow-redirects was locked to 1.5.10 in #1993 and was reverted unintentionally in #1816. And #2570 locked it again.

The reason is that from follow-redirects@1.6.0, the request will be aborted when redirecting. See https://github.com/follow-redirects/follow-redirects/commit/7a0a68327f52d9084fad710fc851d256448a4f15. Then axios can't emit the error, which results in test case "should support max redirects" failed.

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
Thanks for unpinning (see also https://github.com/axios/axios/issues/2691).

**Comment by RubenVerborgh** [comment]
The error message might not necessarily be a constant though; let's think of a contract that we can sustain. Such as an error code or so.

**Comment by chinesedfan** [comment]
@RubenVerborgh Yeah, waiting for your good news about the error code.

**Comment by RubenVerborgh** [comment]
@chinesedfan As as of `follow-redirects@1.10.0`, you can check for `err.code !== 'ERR_FR_TOO_MANY_REDIRECTS'`.

**Comment by chinesedfan** [comment]
@RubenVerborgh Updated with the error code. Thanks for your quick response.

**Pull request merged**
