### PR TITLE
Fix https request on http proxy variant 2

### PR DESCRIPTION
**Pull request by Sitronik**
Fixed https request on http proxy, about this issue you can read [here](https://github.com/axios/axios/pull/1232#issuecomment-357698677)

### CODE REVIEW

**Comment by prokopsimek** [comment]
Does not work for me. :(

**Comment by prokopsimek** [comment]
@Sitronik With username and password.

**Comment by Sitronik** [comment]
@prokopsimek Can you show me the code you are using?

**Comment by prokopsimek** [comment]
@Sitronik I'm sorry, it's too late to remember the piece of code. I know that I use this workaround: https://github.com/axios/axios/issues/925#issuecomment-359982190 and it works.

I guess I tried something like this:

```
const req = await axios({
  url: 'https://somedomain.com',
  proxy: {
    host: '89.151.146.7',
    port: 6060,
    auth: {
      username: 'myname',
      password: 'mypass',
    },
  },
});
```
ref.: https://github.com/axios/axios/issues/925#issue-232289309

...with reference to your master branch with this fix.

**Comment by jasonsaayman** [comment]
Hi

Thanks for the pull request but I don't think that we should be adding dependancies to the repo without a lot of careful thought. Also there are not test and this is a old pull request that is stale.

Thanks

**Pull request closed without merging**
